#!/usr/bin/env python3
"""
YOU ARE NOT IN YOUR BODY — The Self Is a Predictive Model
Embodied cognition and the constructed nature of selfhood.

An original Platinum-house procedural visual essay.

CENTRAL CLAIM
-------------
The experience of being a self located in a body is not a given. It is a
prediction — a controlled hallucination generated by the brain to organize
experience. The rubber hand illusion, the body swap illusion, and
out-of-body experiences all demonstrate that the self can be displaced,
extended, and remodeled in minutes.

For neuroscience: the self is not a thing. It is a model. And models can
be updated. This is the mechanism of healing.

FILM THESIS
-----------
The modern picture often runs:

there is a self in a body
→ the body is the container
→ the self is where the body is

The constructed self picture can be staged as:

the brain predicts a body
→ the prediction is the experience of being in a body
→ the prediction can be updated
→ the self-model extends beyond the body
→ the self is not a location — it is a process

Healing is model update. Liberation is model flexibility.

HOUSE RULES
-----------
• Every shot lasts 5-10 seconds.
• Every shot performs a visible transformation.
• Clean ivory gallery field.
• No slideshow compositions.
• Sparse labels only.
• Mature frame near u=0.72.
• Continuity object: a body outline that shifts, duplicates, and relocates.
• Final reveal: the outline was never a container — it was a drawing.

OUTPUT
------
output_constructed_self/
  frames/
  scenes/
  constructed_self.mp4
  narration_timeline.json
  contact_sheet.jpg
"""

from __future__ import annotations
import argparse, json, math, random, shutil, subprocess
from dataclasses import asdict, dataclass
from pathlib import Path; from typing import Callable
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "output_constructed_self"
FRAMES = OUTPUT / "frames"; SCENES_DIR = OUTPUT / "scenes"
DEFAULT_WIDTH=1280; DEFAULT_HEIGHT=720; DEFAULT_FPS=10
IVORY=(249,247,241); WHITE=(255,254,250); INK=(29,33,39); SOFT_INK=(86,91,98)
CYAN=(57,156,180); GOLD=(194,156,72); PALE_GOLD=(236,219,175)
GREEN=(70,139,99); CRIMSON=(162,58,69); VIOLET=(109,83,153)
FONT_SERIF="/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf"
FONT_SERIF_BOLD="/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf"
FONT_SANS="/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_SANS_BOLD="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

def clamp(x,lo=0.0,hi=1.0): return max(lo,min(hi,x))
def lerp(a,b,t): return a+(b-a)*clamp(t)
def mix(a,b,t): t=clamp(t); return tuple(int(lerp(x,y,t)) for x,y in zip(a,b))
def smoothstep(a,b,x):
    if a==b: return 1.0 if x>=b else 0.0
    q=clamp((x-a)/(b-a)); return q*q*(3-2*q)
def ease(t): t=clamp(t); return .5-.5*math.cos(math.pi*t)
def font(path,size):
    for c in (path,FONT_SERIF,FONT_SANS):
        try: return ImageFont.truetype(c,size)
        except OSError: pass
    return ImageFont.load_default()
def layer(size): return Image.new("RGBA",size,(0,0,0,0))
def field(w,h,seed):
    rng=np.random.default_rng(seed)
    arr=np.empty((h,w,3),dtype=np.float32); arr[:]=IVORY
    arr+=rng.normal(0,.9,(h,w,1)); yy,xx=np.mgrid[0:h,0:w]
    halo=np.exp(-(((xx-w*.5)/(w*.37))**2+((yy-h*.40)/(h*.31))**2)*2)
    arr[...,1]+=halo*3.2; arr[...,2]+=halo*4.6
    return Image.fromarray(np.clip(arr,0,255).astype(np.uint8),"RGB").convert("RGBA")
def centered(d,xy,text,fnt,fill=INK): d.text(xy,text,font=fnt,fill=fill,anchor="mm")
def seal(im,title,subtitle="",color=INK):
    w,h=im.size; d=ImageDraw.Draw(im)
    centered(d,(w/2,h*.875),title,font(FONT_SERIF_BOLD,max(22,int(h*.04))),color)
    if subtitle: centered(d,(w/2,h*.923),subtitle,font(FONT_SANS,max(13,int(h*.019))),SOFT_INK)
def border(im):
    w,h=im.size; d=ImageDraw.Draw(im)
    d.rounded_rectangle((26,26,w-26,h-26),radius=18,outline=(*INK,45),width=2)
def glow_circle(im,x,y,r,color,alpha=170,blur=14):
    gl=layer(im.size); gd=ImageDraw.Draw(gl)
    gd.ellipse((x-r,y-r,x+r,y+r),fill=(*color,alpha))
    im.alpha_composite(gl.filter(ImageFilter.GaussianBlur(blur)))
    fg=layer(im.size)
    ImageDraw.Draw(fg).ellipse((x-r*.34,y-r*.34,x+r*.34,y+r*.34),
        fill=(*mix(color,WHITE,.35),min(255,alpha+50)))
    im.alpha_composite(fg)
def glow_line(im,pts,color,width=4,alpha=210,blur=11):
    if len(pts)<2: return
    gl=layer(im.size); gd=ImageDraw.Draw(gl)
    gd.line(pts,fill=(*color,alpha),width=width*3,joint="curve")
    im.alpha_composite(gl.filter(ImageFilter.GaussianBlur(blur)))
    fg=layer(im.size)
    ImageDraw.Draw(fg).line(pts,fill=(*mix(color,WHITE,.08),min(255,alpha+25)),width=width,joint="curve")
    im.alpha_composite(fg)
def partial(pts,a):
    if not pts: return []; a=clamp(a)
    if a>=1: return pts
    k=a*(len(pts)-1); i=int(k); f=k-i
    out=list(pts[:i+1])
    if i+1<len(pts): p,q=pts[i],pts[i+1]; out.append((lerp(p[0],q[0],f),lerp(p[1],q[1],f)))
    return out

def draw_body_outline(d,cx,cy,scale=1.0,color=INK,alpha=180):
    d.ellipse((cx-27*scale,cy-130*scale,cx+27*scale,cy-78*scale),
              outline=(*color,alpha),width=max(2,int(4*scale)))
    d.line((cx,cy-78*scale,cx,cy+35*scale),fill=(*color,alpha),width=max(3,int(6*scale)))
    d.line((cx-68*scale,cy-35*scale,cx+68*scale,cy-35*scale),fill=(*color,alpha),width=max(3,int(5*scale)))
    d.line((cx-50*scale,cy+35*scale,cx-25*scale,cy+80*scale),fill=(*color,alpha),width=max(3,int(5*scale)))
    d.line((cx+50*scale,cy+35*scale,cx+25*scale,cy+80*scale),fill=(*color,alpha),width=max(3,int(5*scale)))

def vis_rubber(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    d.ellipse((cx-90*q,cy-20*q,cx-20*q,cy+20*q),outline=(*INK,int(180*q)),width=3)
    d.ellipse((cx+20*q,cy-20*q,cx+90*q,cy+20*q),outline=(*GOLD,int(180*q)),width=3)
    d.line((cx-90*q,cy,cx-20*q,cy),fill=(*INK,int(160*q)),width=2)
    d.line((cx+20*q,cy,cx+90*q,cy),fill=(*GOLD,int(160*q)),width=2)
    glow_circle(im,cx-55*q,cy,8,CYAN,int(160*q),7)
    seal(im,"THE RUBBER HAND ILLUSION","stroke a fake hand — it becomes yours in seconds")

def vis_swap(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    d.ellipse((cx-80*q,cy-40*q,cx-20*q,cy+40*q),outline=(*CYAN,int(170*q)),width=3)
    d.ellipse((cx+20*q,cy-40*q,cx+80*q,cy+40*q),outline=(*CYAN,int(170*q)),width=3)
    if q>.3: glow_circle(im,cx,cy,12,GOLD,int(200*(q-.3)/.7),10)
    seal(im,"THE BODY SWAP","you can feel located in another body")

def vis_obe(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    d.ellipse((cx-40,cy-60,cx+40,cy+60),outline=(*INK,int(180*(1-q))),width=3)
    if q>.2:
        qc=(q-.2)/.8; glow_circle(im,cx,cy-80*qc,12,GOLD,int(200*qc),10)
        d.line((cx,cy-55,cx,cy-80*qc),fill=(*GOLD,int(160*qc)),width=2)
    seal(im,"OUT-OF-BODY EXPERIENCE","the self can be displaced from the body")

def vis_prediction_self(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    glow_circle(im,cx,cy,16,CYAN,int(200*q),14)
    for i in range(6):
        a=i*math.tau/6+t*.06; qc=clamp(q*3-i*.1)
        if qc<=0: continue
        x=cx+math.cos(a)*(30+100*qc); y=cy+math.sin(a)*(30+100*qc)*.35
        d.line((cx,cy,x,y),fill=(*CYAN,int(150*qc)),width=2)
    seal(im,"PREDICTIVE PROCESSING OF BODY","the prediction IS the experience of being in a body")

def vis_kancukas_self(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    labels=['AGENCY','KNOWLEDGE','TIME','CAUSALITY']
    for i,l in enumerate(labels):
        qc=clamp(q*4-i*.1)
        if qc<=0: continue
        x=lerp(w*.25,w*.75,i/3); y=lerp(h*.25,h*.60,i/3)
        col=mix(CRIMSON,INK,i/3)
        d.ellipse((x-25*qc,y-15*qc,x+25*qc,y+15*qc),outline=(*col,int(170*qc)),width=2)
        centered(d,(x,y),l,font(FONT_SANS_BOLD,int(h*.020)),col)
    seal(im,"KANCUKAS AS SELF-PARAMETERS","limited agency, knowledge, time, causality")

def vis_plasticity(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    pts=[(cx+math.cos(i*math.tau/30)*(30+110*q),cy+math.sin(i*math.tau/30)*(30+110*q)*.35) for i in range(31)]
    glow_line(im,partial(pts,q),GOLD,4,220,14)
    for i in range(3):
        a=(i-1)*.5; qc=clamp(q*3-i*.12)
        if qc<=0: continue
        x=cx+math.cos(a)*100*qc; y=cy+math.sin(a)*100*qc
        d.ellipse((x-10*qc,y-10*qc,x+10*qc,y+10*qc),fill=(*GREEN,int(160*qc)))
    seal(im,"THE SELF IS PLASTIC","updated in minutes — the mechanism of healing")

def vis_self_model(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    d.ellipse((cx-60*q,cy-80*q,cx+60*q,cy+80*q),outline=(*GOLD,int(200*q)),width=3)
    d.ellipse((cx-40*q,cy-55*q,cx+40*q,cy+55*q),outline=(*CYAN,int(160*q)),width=2)
    d.ellipse((cx-20*q,cy-30*q,cx+20*q,cy+30*q),outline=(*INK,int(140*q)),width=2)
    labels=['NARRATIVE','BODILY','MINIMAL']
    for i,l in enumerate(labels):
        y=cy-70*q+i*50; col=[INK,CYAN,GOLD][i]
        centered(d,(cx-90*q,y),l,font(FONT_SANS_BOLD,int(h*.020)),(*col,int(200*q)))
    seal(im,"THE SELF IS A MODEL","not a thing — a nested hierarchy of predictions about who you are")

def vis_self_boundary(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    d.ellipse((cx-100*q,cy-80*q,cx+100*q,cy+80*q),outline=(*GOLD,int(200*q)),width=3)
    d.ellipse((cx-60*q,cy-48*q,cx+60*q,cy+48*q),outline=(*CYAN,int(160*q)),width=2)
    d.ellipse((cx-25*q,cy-20*q,cx+25*q,cy+20*q),outline=(*INK,int(140*q)),width=2)
    centered(d,(cx,cy-90*q),'THE SELF BOUNDARY',font(FONT_SANS_BOLD,int(h*.022)),GOLD)
    centered(d,(cx,cy),'I',font(FONT_SERIF_BOLD,int(h*.060)),(*INK,int(200*q)))
    seal(im,"THE SELF IS A BOUNDARY","the self is not a thing — it is the boundary between me and not-me")

def vis_no_self(im,u,t,p):
    w,h=im.size; cx,cy=w*.50,h*.40; q=ease(u); d=ImageDraw.Draw(im)
    pts=[(cx+math.cos(i*math.tau/35)*(30+120*q),cy+math.sin(i*math.tau/35)*(30+120*q)*.35) for i in range(36)]
    glow_line(im,partial(pts,q),GOLD,4,220,16)
    for i in range(6):
        a=i*math.tau/6+r*.4; rad=40+100*q
        x=cx+math.cos(a)*rad; y=cy+math.sin(a)*rad*.35
        col=mix(CYAN,CRIMSON,i/5); d.line((cx,cy,x,y),fill=(*col,int(150*q)),width=2)
        glow_circle(im,x,y,5+3*q,col,int(140*q),7)
    centered(d,(cx,cy),chr(8709),font(FONT_SERIF_BOLD,int(h*.080)),(*GOLD,int(200*q)))
    seal(im,"NO PERMANENT SELF","the self is not a thing — it is a process of modeling that never stops")

def vis_bridge(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    left=(w*.30,h*.40); right=(w*.70,h*.40); q=ease(u)
    xs=[left[0]-80,left[0],left[0]+80]
    for i,x in enumerate(xs): glow_circle(im,x,left[1],10,[VIOLET,CYAN,GREEN][i],145,8)
    for rr in range(35,150,25):
        d.ellipse((right[0]-rr,right[1]-rr*.62,right[0]+rr,right[1]+rr*.62),
                  outline=(*GOLD,int(75*q*(1-rr/170))),width=3)
    centered(d,(left[0],h*.68),"NEUROSCIENCE",font(FONT_SANS_BOLD,13),CYAN)
    centered(d,(right[0],h*.68),"KĀṦMĪRA ŚAIVISM",font(FONT_SANS_BOLD,13),GOLD)
    glow_line(im,partial([left,(w*.50,h*.20),right],q),VIOLET,4,170,11)
    seal(im,"BOTH TRADITIONS AGREE: THE SELF IS NOT A THING","neuroscience and nonduality converge on the constructed nature of self")

def vis_caution(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    rows=[
        ("THE SELF IS AN ILLUSION","NOT SUPPORTED — IT IS A CONSTRUCT",CRIMSON),
        ("THE SELF CAN BE UPDATED","SUPPORTED BY NEUROPLASTICITY",GREEN),
        ("THE SELF IS LOCATED IN THE BRAIN","NOT SUPPORTED — IT IS DISTRIBUTED",CRIMSON),
        ("THE BODY SWAP IS A REAL PHENOMENON","SUPPORTED BY LAB EXPERIMENTS",CYAN),
    ]
    q=ease(u)
    for i,(claim,status,col) in enumerate(rows):
        local=clamp(q*len(rows)-i); y=h*(.23+i*.13)
        d.rounded_rectangle((w*.14,y-28,w*.86,y+28),radius=14,
            fill=(*mix(WHITE,col,.10),int(220*local)),outline=(*col,int(180*local)),width=2)
        centered(d,(w*.39,y),claim,font(FONT_SANS_BOLD,14),INK)
        centered(d,(w*.74,y),status,font(FONT_SANS_BOLD,14),col)
    seal(im,"THE SELF IS NOT AN ILLUSION — IT IS A MODEL THAT CAN BE UPDATED","this is the most hopeful finding in cognitive science")

VISUALS = {
    "rubber":vis_rubber,"swap":vis_swap,"obe":vis_obe,"prediction":vis_prediction_self,
    "kancukas":vis_kancukas_self,"plasticity":vis_plasticity,
    "self_model":vis_self_model,"self_boundary":vis_self_boundary,"no_self":vis_no_self,
    "bridge":vis_bridge,"caution":vis_caution,
}

@dataclass
class Scene:
    title:str; narration:str; duration:float; visual:str; params:dict

SCENES = [
    Scene("The Rubber Hand Illusion","Stroke a fake hand — it becomes yours in seconds.",9.0,"rubber",{}),
    Scene("The Plastic Body","If a fake hand can become yours, what else can? The self-model is extendable.",8.5,"rubber",{}),
    Scene("The Body Schema","Your brain maintains a constantly updated model of your body. That model IS your body.",9.0,"rubber",{}),
    Scene("The Body Swap","You can feel located in another body.",8.5,"swap",{}),
    Scene("Virtual Embodiment","In VR, you can inhabit any body. The brain accepts it in minutes.",8.5,"swap",{}),
    Scene("The Empathic Self","You can feel another's body as your own. The self-model extends beyond the skin.",9.0,"swap",{}),
    Scene("Out-of-Body Experience","The self can be displaced from the body.",8.5,"obe",{}),
    Scene("The Floating I","When the self-model detaches from the body, the 'I' floats free.",9.0,"obe",{}),
    Scene("The Dislocated Self","OBEs prove the self is not located in the body. It is a model.",9.0,"obe",{}),
    Scene("Predictive Processing of Body","The prediction IS the experience of being in a body.",9.0,"prediction",{}),
    Scene("The Controlled Hallucination","Your body is a controlled hallucination. Very controlled. Very useful.",9.0,"prediction",{}),
    Scene("The Bodily Prediction","The brain predicts body state. The prediction is the feeling of being embodied.",9.0,"prediction",{}),
    Scene("Kancukas as Self-Parameters","Limited agency, knowledge, time, causality.",9.0,"kancukas",{}),
    Scene("The Parameters of Self","The kancukas describe the constraints that make a self feel real.",9.0,"kancukas",{}),
    Scene("The Finite Self","The self appears finite because it models finitude. The model is not the whole.",9.0,"kancukas",{}),
    Scene("The Self is Plastic","Updated in minutes — the mechanism of healing.",9.0,"plasticity",{}),
    Scene("Neuroplasticity of Self","The self-model can change. This is the mechanism of healing and growth.",9.0,"plasticity",{}),
    Scene("The Flexible I","A flexible self-model is a healthy self-model. Rigidity is pathology.",9.0,"plasticity",{}),
    Scene("The Self is a Model","Not a thing — a nested hierarchy of predictions about who you are.",9.5,"self_model",{}),
    Scene("Three Layers","Minimal self, bodily self, narrative self — each is a level of the model.",9.0,"self_model",{}),
    Scene("The Predictive Hierarchy","The self is not one thing. It is a nested stack of predictions.",9.5,"self_model",{}),
    Scene("The Self is a Boundary","The self is not a thing — it is the boundary between me and not-me.",9.5,"self_boundary",{}),
    Scene("The Skin vs The Model","The boundary of the self is not the skin. It is the range of the model.",9.5,"self_boundary",{}),
    Scene("Extending the Boundary","Tools, possessions, others — all integrated into the self-model.",9.0,"self_boundary",{}),
    Scene("No Permanent Self","The self is not a thing — it is a process of modeling that never stops.",10.0,"no_self",{}),
    Scene("The Open Process","The self is not an entity. It is an activity. The activity of self-ing.",10.0,"no_self",{}),
    Scene("The Freedom in Fluidity","When the self-model becomes flexible, healing happens. The cage opens.",10.0,"no_self",{}),
    Scene("Science Bridge","Neuroscience and nonduality converge on the constructed nature of self.",9.0,"bridge",{}),
    Scene("The Convergence","These two traditions — one empirical, one contemplative — agree: the self is not a thing.",9.5,"bridge",{}),
    Scene("The Shared Insight","The impermanence of self is not a philosophical position. It is an observed fact.",9.5,"bridge",{}),
    Scene("Caution","The self is not an illusion — it is a model that can be updated.",9.0,"caution",{}),
    Scene("Not Nihilism","The constructed self is not no self. It is a self that can change.",8.5,"caution",{}),
    Scene("The Hope","If the self can change, healing is always possible. The cage can always open.",9.0,"caution",{}),
    Scene("Closing","You are not in your body. The body is a model in consciousness. The self is not a thing — it is a process of modeling that never stops. And when the model becomes flexible enough, you realize: the self was never a prison. It was a drawing. And you are the artist.",10.0,"no_self",{}),
]

def render_frame(s,fi,fc,w,h,seed):
    u=fi/max(1,fc-1); t=u*s.duration
    im=field(w,h,seed); VISUALS[s.visual](im,u,t,s.params); border(im)
    return im.convert("RGB")
def ffmpeg_path():
    exe=shutil.which("ffmpeg")
    if not exe: raise RuntimeError("ffmpeg required")
    return exe
def encode_scene(idx,fps):
    fd=FRAMES/f"scene_{idx:03d}"; o=SCENES_DIR/f"scene_{idx:03d}.mp4"
    subprocess.run([ffmpeg_path(),"-y","-framerate",str(fps),"-i",str(fd/"%05d.jpg"),
        "-c:v","libx264","-preset","medium","-crf","18","-pix_fmt","yuv420p","-movflags","+faststart",str(o)],
        check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    return o
def render_scene(idx,s,fps,w,h,prev):
    fd=FRAMES/f"scene_{idx:03d}"; fd.mkdir(parents=True,exist_ok=True); SCENES_DIR.mkdir(parents=True,exist_ok=True)
    cnt=max(2,round(s.duration*fps))
    if prev:
        for oi,fi in enumerate([0,int(cnt*.33),int(cnt*.72),cnt-1]):
            render_frame(s,fi,cnt,w,h,idx*10000+fi).save(fd/f"preview_{oi:02d}.jpg",quality=95)
        return fd
    for fi in range(cnt):
        p=fd/f"{fi:05d}.jpg"
        if p.exists(): continue
        render_frame(s,fi,cnt,w,h,idx*10000+fi).save(p,quality=95,subsampling=0)
    return encode_scene(idx,fps)
def concat(paths):
    txt=OUTPUT/"concat.txt"; txt.write_text("\n".join(f"file '{p.resolve()}'" for p in paths),encoding="utf-8")
    o=OUTPUT/"constructed_self.mp4"
    subprocess.run([ffmpeg_path(),"-y","-f","concat","-safe","0","-i",str(txt),"-c","copy","-movflags","+faststart",str(o)],
        check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    return o
def export_timeline():
    cursor=0.0; recs=[]
    for i,s in enumerate(SCENES,1):
        r=asdict(s); r["scene_id"]=f"scene_{i:03d}"; r["start_seconds"]=round(cursor,3)
        cursor+=s.duration; r["end_seconds"]=round(cursor,3); recs.append(r)
    p=OUTPUT/"narration_timeline.json"; p.write_text(json.dumps({"title":"you are not in your body",
        "subtitle":"the self is a predictive model","scene_count":len(SCENES),
        "runtime_seconds":round(cursor,3),"shot_duration_range":[5,10],
        "continuity_object":"shifting body outline that duplicates and relocates",
        "visual_arc":["rubber hand","body swap","OBE","prediction","kancukas","plasticity"],
        "scenes":recs},indent=2,ensure_ascii=False),encoding="utf-8")
    return p
def contact_sheet(w,h):
    tw=320; th=int(tw*h/w); cols=4; rows=math.ceil(len(SCENES)/4); ch=th+48
    s=Image.new("RGB",(cols*tw,rows*ch),IVORY); d=ImageDraw.Draw(s); lf=font(FONT_SANS_BOLD,14)
    for i,sc in enumerate(SCENES,1):
        cnt=max(2,round(sc.duration*DEFAULT_FPS))
        im=render_frame(sc,int(cnt*.72),cnt,w,h,i*10000+72); im.thumbnail((tw,th))
        sl=i-1; x=(sl%cols)*tw; y=(sl//cols)*ch; s.paste(im,(x,y))
        d.text((x+8,y+th+7),f"{i:02d}  {sc.title}",font=lf,fill=INK)
    p=OUTPUT/"contact_sheet.jpg"; s.save(p,quality=94); return p
def parse_args():
    p=argparse.ArgumentParser()
    p.add_argument("--fps",type=int,default=DEFAULT_FPS); p.add_argument("--width",type=int,default=DEFAULT_WIDTH)
    p.add_argument("--height",type=int,default=DEFAULT_HEIGHT); p.add_argument("--scene",type=int)
    p.add_argument("--preview",action="store_true"); p.add_argument("--no-contact-sheet",action="store_true")
    return p.parse_args()
def main():
    a=parse_args(); OUTPUT.mkdir(parents=True,exist_ok=True); FRAMES.mkdir(parents=True,exist_ok=True); SCENES_DIR.mkdir(parents=True,exist_ok=True)
    print(f"Timeline: {export_timeline()}"); print(f"Scenes: {len(SCENES)}"); print(f"Runtime: {sum(s.duration for s in SCENES)/60:.2f} min")
    if a.scene:
        if not 1<=a.scene<=len(SCENES): raise ValueError("scene out of range")
        print(render_scene(a.scene,SCENES[a.scene-1],a.fps,a.width,a.height,a.preview)); return
    rendered=[]
    for i,s in enumerate(SCENES,1):
        print(f"[{i:02d}/{len(SCENES):02d}] {s.title} ({s.duration:.1f}s)")
        r=render_scene(i,s,a.fps,a.width,a.height,a.preview)
        if not a.preview: rendered.append(r)
    if not a.no_contact_sheet: print(f"Contact: {contact_sheet(a.width,a.height)}")
    if not a.preview: print(f"Final: {concat(rendered)}")
if __name__=="__main__": main()
