#!/usr/bin/env python3
"""
THE WHOLE CAN ACT BEFORE ANY PART UNDERSTANDS IT
A complete Platinum-house procedural visual essay.

Source adapted from:
expansion-essays/05_the_whole_can_act_before_any_part_understands_it.md

DESIGN CONTRACT
---------------
• Every shot lasts 5–10 seconds.
• Every shot visibly performs the narrated operation.
• Clean white developmental-biology field; deep field only for attractor scenes.
• No static slide layouts and no decorative loops.
• Cyan = local cellular mechanism / calcium / voltage
• Gold = global constraint / positional information / organism-level form
• Green = successful integration / repair / regulated outcome
• Crimson = competing axis / misalignment / failed coordination
• Violet = gene-regulatory interpretation / latent fate
• Graphite = geometry / mechanics / tissue architecture
• Sparse typography: terms function as seals, never paragraphs.
• Each mature frame around u=0.72 should work as a still.
• Continuity object: a gold constraint field generated by parts and fed back into them.
• The whole must never be drawn as a ghost, commander, or hidden homunculus.
• Geometry, gradients, mechanics, and distributed feedback are the causal language.

OUTPUT
------
output_whole_before_part/
  frames/scene_001/*.jpg
  scenes/scene_001.mp4
  the_whole_can_act_before_any_part_understands_it.mp4
  narration_timeline.json
  contact_sheet.jpg

REQUIREMENTS
------------
pip install pillow numpy
ffmpeg must be on PATH.

USAGE
-----
python the_whole_can_act_before_any_part_understands_it_platinum.py
python the_whole_can_act_before_any_part_understands_it_platinum.py --preview
python the_whole_can_act_before_any_part_understands_it_platinum.py --scene 8
python the_whole_can_act_before_any_part_understands_it_platinum.py --fps 12 --width 1920 --height 1080
"""

from __future__ import annotations
import argparse, json, math, random, shutil, subprocess
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Callable
import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT=Path(__file__).resolve().parent
OUTPUT=ROOT/"output_whole_before_part"
FRAMES=OUTPUT/"frames"
SCENES_DIR=OUTPUT/"scenes"

DEFAULT_WIDTH=1280
DEFAULT_HEIGHT=720
DEFAULT_FPS=10

WHITE=(248,247,243); PAPER=(242,239,232); INK=(29,31,35); SOFT_INK=(84,88,94)
SILVER=(177,184,190); PALE_SILVER=(224,227,229)
CYAN=(55,153,181); PALE_CYAN=(192,226,233)
GOLD=(194,153,68); PALE_GOLD=(235,218,175)
GREEN=(70,139,98); PALE_GREEN=(194,225,206)
CRIMSON=(158,52,66); PALE_CRIMSON=(230,192,198)
VIOLET=(104,79,146); PALE_VIOLET=(216,205,232)
LAPIS=(48,72,124); VOID=(22,25,31)

FONT_SERIF="/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf"
FONT_SERIF_BOLD="/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf"
FONT_SANS="/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_SANS_BOLD="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

def clamp(x,lo=0,hi=1): return max(lo,min(hi,x))
def lerp(a,b,t): return a+(b-a)*t
def mix(a,b,t):
    t=clamp(t); return tuple(int(lerp(x,y,t)) for x,y in zip(a,b))
def smoothstep(a,b,x):
    if a==b:return 1.0 if x>=b else 0.0
    q=clamp((x-a)/(b-a)); return q*q*(3-2*q)
def ease(t): return .5-.5*math.cos(math.pi*clamp(t))
def pulse(t,hz=1,phase=0): return .5+.5*math.sin(math.tau*(hz*t+phase))
def load_font(path,size):
    for p in (path,FONT_SERIF,FONT_SANS):
        try:return ImageFont.truetype(p,size)
        except OSError:pass
    return ImageFont.load_default()
def rgba_layer(size): return Image.new("RGBA",size,(0,0,0,0))
def background(w,h,seed,dark=False):
    rng=np.random.default_rng(seed); base=VOID if dark else WHITE
    arr=np.empty((h,w,3),dtype=np.float32); arr[:]=base
    arr+=rng.normal(0,1.05 if not dark else 1.7,(h,w,1))
    return Image.fromarray(np.clip(arr,0,255).astype(np.uint8),"RGB").convert("RGBA")
def centered_text(d,xy,text,font,fill=INK): d.text(xy,text,font=font,fill=fill,anchor="mm")
def seal(im,title,subtitle="",color=INK,dark=False):
    w,h=im.size; d=ImageDraw.Draw(im)
    centered_text(d,(w/2,h*.875),title,load_font(FONT_SERIF_BOLD,max(22,int(h*.042))),WHITE if dark else color)
    if subtitle:centered_text(d,(w/2,h*.925),subtitle,load_font(FONT_SANS,max(13,int(h*.020))),PALE_SILVER if dark else SOFT_INK)
def border(im,dark=False):
    w,h=im.size
    ImageDraw.Draw(im).rounded_rectangle((25,25,w-25,h-25),radius=17,outline=(*(WHITE if dark else INK),42),width=2)
def glow_line(im,pts,color,width=4,glow=14,alpha=225):
    if len(pts)<2:return
    layer=rgba_layer(im.size); d=ImageDraw.Draw(layer)
    d.line(pts,fill=(*color,alpha),width=width,joint="curve")
    im.alpha_composite(layer.filter(ImageFilter.GaussianBlur(glow))); im.alpha_composite(layer)
def glow_circle(im,cx,cy,r,color,alpha=180,blur=18):
    layer=rgba_layer(im.size); d=ImageDraw.Draw(layer)
    d.ellipse((cx-r,cy-r,cx+r,cy+r),fill=(*color,alpha))
    im.alpha_composite(layer.filter(ImageFilter.GaussianBlur(blur)))
    core=rgba_layer(im.size)
    ImageDraw.Draw(core).ellipse((cx-r*.42,cy-r*.42,cx+r*.42,cy+r*.42),fill=(*mix(color,WHITE,.28),min(255,alpha+40)))
    im.alpha_composite(core)
def partial_polyline(points,progress):
    progress=clamp(progress)
    if len(points)<2:return points
    lengths=[math.dist(a,b) for a,b in zip(points[:-1],points[1:])]
    total=sum(lengths); target=total*progress; out=[points[0]]; walked=0
    for i,L in enumerate(lengths):
        if walked+L<=target: out.append(points[i+1]); walked+=L
        else:
            q=0 if L==0 else (target-walked)/L
            ax,ay=points[i]; bx,by=points[i+1]
            out.append((lerp(ax,bx,q),lerp(ay,by,q))); break
    return out
def arrow(d,start,end,color=INK,width=3,head=12):
    d.line((*start,*end),fill=color,width=width)
    a=math.atan2(end[1]-start[1],end[0]-start[0])
    for delta in (2.55,-2.55):
        p=(end[0]+math.cos(a+delta)*head,end[1]+math.sin(a+delta)*head)
        d.line((*end,*p),fill=color,width=width)
def cell(d,x,y,r,color,alpha=220,nucleus=True):
    d.ellipse((x-r,y-r,x+r,y+r),fill=(*mix(WHITE,color,.16),alpha),outline=(*color,min(255,alpha+10)),width=3)
    if nucleus:d.ellipse((x-r*.26,y-r*.26,x+r*.26,y+r*.26),fill=(*mix(color,VIOLET,.35),160))
def embryo_points(w,h,cols=13,rows=8):
    pts=[]
    for j in range(rows):
        for i in range(cols):
            x=w*(.13+i*(.74/(cols-1))); y=h*(.18+j*(.48/(rows-1)))
            pts.append((x,y,i,j))
    return pts
def constraint_field(im,phase=0,alpha=85):
    w,h=im.size
    for j in range(9):
        pts=[]
        for i in range(180):
            q=i/179
            x=lerp(w*.08,w*.92,q)
            y=h*(.17+j*.058)+math.sin(q*math.tau*2+phase+j*.4)*10
            pts.append((x,y))
        glow_line(im,pts,GOLD,2,7,alpha)

@dataclass
class Scene:
    title:str
    narration:str
    duration:float
    visual:str
    params:dict

def visual_local_signals(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    pts=embryo_points(w,h)
    for x,y,i,j in pts: cell(d,x,y,10,CYAN,180)
    focus=pts[3*13+2]
    glow_circle(im,focus[0],focus[1],18,GOLD,150,10)
    signals=[("PRESSURE",INK,-95,-75),("VOLTAGE",CYAN,100,-70),("CHEMISTRY",VIOLET,-95,80),("CONTACT",GREEN,105,78)]
    for idx,(txt,col,ox,oy) in enumerate(signals):
        q=smoothstep(idx*.1,.62+idx*.06,u)
        x=focus[0]+ox;y=focus[1]+oy
        arrow(d,(x,y),focus,(*col,int(170*q)),3,9)
        if q>.68:centered_text(d,(x,y),txt,load_font(FONT_SANS_BOLD,int(h*.013)),col)
    seal(im,"NO CELL UNDERSTANDS THE BODY","local signals can still participate in one coherent form")

def visual_upward_chain(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    stages=[("GENES",VIOLET),("PROTEINS",CYAN),("VOLTAGE",GOLD),("FORCE",INK),("TISSUE",GREEN)]
    xs=[w*(.12+i*.19) for i in range(5)]
    for i,((txt,col),x) in enumerate(zip(stages,xs)):
        q=smoothstep(i*.1,.60+i*.07,u)
        d.ellipse((x-34*q,h*.40-34*q,x+34*q,h*.40+34*q),fill=(*mix(WHITE,col,.17),int(220*q)),outline=(*col,int(180*q)),width=3)
        if q>.65:centered_text(d,(x,h*.58),txt,load_font(FONT_SANS_BOLD,int(h*.013)),col)
        if i>0:arrow(d,(xs[i-1]+34,h*.40),(x-34,h*.40),mix(stages[i-1][1],col,.5),3,9)
    seal(im,"UPWARD CAUSATION IS INDISPENSABLE","but once a pattern exists, does it become causally irrelevant?")

def visual_constraint_examples(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # riverbank
    d.line((w*.08,h*.28,w*.32,h*.22),fill=(*INK,180),width=7)
    d.line((w*.08,h*.52,w*.32,h*.58),fill=(*INK,180),width=7)
    glow_line(im,partial_polyline([(w*.08,h*.40),(w*.20,h*.34),(w*.32,h*.40)],ease(u)),CYAN,5,12,200)
    # musical key
    for i in range(7):
        x=w*.44+i*22; y=h*.42-math.sin(i*.8)*35
        d.ellipse((x-7,y-7,x+7,y+7),fill=(*GOLD,170))
    # traffic
    d.line((w*.69,h*.26,w*.91,h*.26),fill=(*INK,120),width=7)
    d.line((w*.69,h*.52,w*.91,h*.52),fill=(*INK,120),width=7)
    for i in range(6):
        x=w*.71+i*38; y=h*.26 if i%2==0 else h*.52
        d.rounded_rectangle((x-12,y-7,x+12,y+7),radius=4,fill=(*GREEN,190))
    seal(im,"THE WHOLE STRUCTURES LOCAL POSSIBILITY","constraint is not a second force added to physics")

def visual_axis_field(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    pts=embryo_points(w,h)
    q=ease(u)
    for x,y,i,j in pts:
        pos=i/12
        col=mix(CYAN,GOLD,pos)
        cell(d,x,y,9,col,180,False)
    # calcium tracks
    for row in (2,4,6):
        line=[(x,y) for x,y,i,j in pts if j==row]
        glow_line(im,partial_polyline(line,q),CYAN,3,10,170)
    # one axis / competing axis
    d.line((w*.22,h*.42,w*.78,h*.42),fill=(*GOLD,int(200*q)),width=6)
    if p.get("competing",False):
        d.line((w*.50,h*.20,w*.50,h*.65),fill=(*CRIMSON,int(190*q)),width=5)
    seal(im,"PARTS CREATE THE FIELD · THE FIELD GOVERNS THE PARTS","global polarity changes what local regions can become")

def visual_positional_information(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    pts=embryo_points(w,h)
    for x,y,i,j in pts:
        pos=i/12
        col=mix(CYAN,GOLD,pos)
        cell(d,x,y,11,col,190,False)
        if i in (2,6,10):
            centered_text(d,(x,y+26),f"{pos:.1f}",load_font(FONT_SANS_BOLD,int(h*.011)),col)
    # same signal interpreted differently
    for i in (2,6,10):
        x=w*(.13+i*(.74/12)); y=h*.48
        arrow(d,(x,h*.67),(x,y+14),VIOLET,3,8)
    seal(im,"THE WHOLE ENTERS EACH PART AS POSITION","a signal means differently depending on where the cell sits")

def visual_mechanical_fold(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    q=ease(u)
    pts=[]
    for i in range(220):
        s=i/219
        x=lerp(w*.12,w*.88,s)
        y=h*.40+math.sin(s*math.pi)*h*.10*q+math.sin(s*math.tau*2)*8
        pts.append((x,y))
    d.line(pts,fill=(*INK,200),width=7)
    # force vectors
    for idx in range(20,200,30):
        x,y=pts[idx]
        arrow(d,(x,y-80),(x,y-10),CYAN,3,9)
    # contact at deepening fold
    if q>.6:
        glow_circle(im,w*.5,h*.48,22,GOLD,140,11)
    seal(im,"THE BODY HELPS CAUSE THE BODY BEFORE IT IS FINISHED","geometry and tension feed back into fate")

def visual_error_correction(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    cx,cy=w*.5,h*.42
    # target outline
    d.ellipse((cx-w*.24,cy-h*.22,cx+w*.24,cy+h*.22),outline=(*GOLD,140),width=4)
    rng=random.Random(72)
    q=ease(u)
    for i in range(90):
        a=rng.random()*math.tau; rr=math.sqrt(rng.random())
        sx=cx+math.cos(a)*w*.31*rr; sy=cy+math.sin(a)*h*.28*rr
        ta=i*math.tau/90
        tx=cx+math.cos(ta)*w*.22; ty=cy+math.sin(ta)*h*.20
        x=lerp(sx,tx,q); y=lerp(sy,ty,q)
        cell(d,x,y,5,mix(CRIMSON,GREEN,q),160,False)
    seal(im,"THE TARGET IS REAL AS A PATTERN OF CORRECTION","different local routes converge on a similar anatomy")

def visual_nested_agents(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    cx,cy=w*.5,h*.42
    levels=[("CELL",55,CYAN),("TISSUE",95,GREEN),("ORGAN",145,GOLD),("ORGANISM",205,VIOLET)]
    for i,(txt,r,col) in enumerate(levels):
        q=smoothstep(i*.12,.62+i*.07,u)
        d.ellipse((cx-r*q,cy-r*.62*q,cx+r*q,cy+r*.62*q),outline=(*col,int(185*q)),width=4)
        if q>.65:centered_text(d,(cx,cy-r*.62*q-17),txt,load_font(FONT_SANS_BOLD,int(h*.013)),col)
    if p.get("misaligned",False):
        glow_circle(im,cx+w*.12,cy,30,CRIMSON,170,12)
    seal(im,"AGENTS ARE NESTED ACROSS SCALES","health requires larger goals to remain causally present to local parts")

def visual_group_context(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    centers=[(w*.25,h*.42),(w*.42,h*.42),(w*.59,h*.42),(w*.76,h*.42)]
    for c in centers:
        d.ellipse((c[0]-50,c[1]-65,c[0]+50,c[1]+65),outline=(*CYAN,180),width=4)
    q=ease(u)
    for i in range(len(centers)-1):
        glow_line(im,[(centers[i][0]+50,centers[i][1]),(centers[i+1][0]-50,centers[i+1][1])],GOLD,4,11,int(180*q))
    # protective field across group
    d.rounded_rectangle((w*.16,h*.24,w*.84,h*.60),radius=45,outline=(*GREEN,int(180*q)),width=5)
    seal(im,"THE REGULATORY WHOLE CAN EXTEND BEYOND ONE ORGANISM","coordination becomes real where it changes trajectories")

def visual_platonic_caution(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    left=(w*.28,h*.42); right=(w*.72,h*.42)
    # form
    d.polygon([(left[0],left[1]-100),(left[0]-90,left[1]+65),(left[0]+90,left[1]+65)],outline=(*VIOLET,190))
    centered_text(d,(left[0],h*.66),"PLATONIC FORM",load_font(FONT_SANS_BOLD,int(h*.015)),VIOLET)
    # physical embryo field
    pts=embryo_points(w*.52,h,8,6)
    for x,y,i,j in pts:
        xx=right[0]-w*.26+x
        cell(d,xx,y,8,CYAN,170,False)
    centered_text(d,(right[0],h*.66),"PHYSICAL CONSTRAINT",load_font(FONT_SANS_BOLD,int(h*.015)),CYAN)
    q=smoothstep(.35,.9,u)
    d.line((w*.49,h*.25,w*.51,h*.58),fill=(*CRIMSON,int(210*q)),width=6)
    seal(im,"ANALOGY IS NOT CONFIRMATION","developmental experiments do not detect an intelligible realm")

def visual_higher_level_reality(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # intervention at global level
    cx,cy=w*.5,h*.42
    pts=embryo_points(w,h)
    for x,y,i,j in pts:cell(d,x,y,8,CYAN,160,False)
    q=ease(u)
    d.ellipse((cx-w*.28,cy-h*.23,cx+w*.28,cy+h*.23),outline=(*GOLD,int(190*q)),width=5)
    # change one global variable and local cells update
    for x,y,i,j in pts:
        if u>.55 and i>7:
            d.ellipse((x-10,y-10,x+10,y+10),outline=(*GREEN,170),width=3)
    seal(im,"A HIGHER LEVEL EARNS REALITY WHEN IT MAKES DIFFERENCES BELOW","the whole need not be a substance; it must be a constraint that works")

def visual_mechanism_return(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    items=[("ION CHANNELS",CYAN),("GAP JUNCTIONS",GOLD),("MECHANOSENSORS",INK),("SIGNALING",GREEN),("GENE REGULATION",VIOLET)]
    cx,cy=w*.5,h*.42
    for i,(txt,col) in enumerate(items):
        a=-math.pi/2+i*math.tau/5
        x=cx+math.cos(a)*w*.28; y=cy+math.sin(a)*h*.25
        q=smoothstep(i*.10,.60+i*.06,u)
        d.rounded_rectangle((x-100*q,y-23*q,x+100*q,y+23*q),radius=14,fill=(*mix(WHITE,col,.14),int(220*q)),outline=(*col,int(180*q)),width=2)
        if q>.65:centered_text(d,(x,y),txt,load_font(FONT_SANS_BOLD,int(h*.012)),col)
        d.line((cx,cy,x,y),fill=(*col,int(120*q)),width=2)
    glow_circle(im,cx,cy,20,GOLD,150,12)
    seal(im,"DOWNWARD CAUSATION WITHOUT A ROUTE IS MYTHOLOGY","mechanism without the whole is only a parts list")

def visual_participation(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    cx,cy=w*.5,h*.42
    # organism field
    d.ellipse((cx-w*.28,cy-h*.24,cx+w*.28,cy+h*.24),outline=(*GOLD,160),width=5)
    # one cell and its allowed actions
    cell(d,cx-w*.10,cy,28,CYAN,220)
    actions=[(cx+w*.05,cy-h*.12,GREEN),(cx+w*.12,cy,GOLD),(cx+w*.04,cy+h*.14,VIOLET)]
    for x,y,col in actions:
        arrow(d,(cx-w*.07,cy),(x,y),col,3,9)
        glow_circle(im,x,y,10,col,120,8)
    seal(im,"THE PART IS ITSELF · AND WHAT IT CAN BE INSIDE THE WHOLE","participation means constrained possibility, not a tiny copy")

def visual_social_constraints(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # people as nodes inside institutional field
    rng=random.Random(33)
    nodes=[]
    for i in range(28):
        x=rng.uniform(w*.16,w*.84); y=rng.uniform(h*.20,h*.64); nodes.append((x,y))
    for i,a in enumerate(nodes):
        for j in (1,5):
            b=nodes[(i+j)%len(nodes)]
            d.line((*a,*b),fill=(*SILVER,55),width=2)
    for i,(x,y) in enumerate(nodes):
        d.ellipse((x-8,y-8,x+8,y+8),fill=(*mix(CYAN,GREEN,i/28),180))
    # constraint channels
    for y,col in [(h*.28,GOLD),(h*.42,CRIMSON),(h*.56,VIOLET)]:
        d.line((w*.12,y,w*.88,y),fill=(*col,120),width=4)
    seal(im,"THE WHOLE IS PRESENT AS A FIELD OF POSSIBILITIES","changing people without changing constraints can restore the same outcome")

def visual_final_agreement(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    pts=embryo_points(w,h)
    q=ease(u)
    for x,y,i,j in pts:
        cell(d,x,y,9,mix(CYAN,GREEN,q),180,False)
    constraint_field(im,t*.12,int(50+120*q))
    # one unfinished organism outline
    d.ellipse((w*.12,h*.13,w*.88,h*.72),outline=(*GOLD,int(100+90*q)),width=5)
    seal(im,"THE WHOLE IS NOT ANOTHER PART WITH A LOUDER VOICE","it is the active agreement through which local lives become one unfinished cause",GREEN)

VISUALS:dict[str,Callable]={
    "local":visual_local_signals,
    "upward":visual_upward_chain,
    "constraint":visual_constraint_examples,
    "axis":visual_axis_field,
    "position":visual_positional_information,
    "fold":visual_mechanical_fold,
    "correction":visual_error_correction,
    "nested":visual_nested_agents,
    "group":visual_group_context,
    "plato":visual_platonic_caution,
    "reality":visual_higher_level_reality,
    "mechanism":visual_mechanism_return,
    "participation":visual_participation,
    "social":visual_social_constraints,
    "final":visual_final_agreement,
}

SCENES:list[Scene]=[
    Scene("No understanding","No cell in an embryo understands the body.",6.5,"local",{}),
    Scene("Local signals","A cell near the edge receives local signals.",6.0,"local",{}),
    Scene("Pressure voltage chemistry","It feels pressure, voltage, chemical concentration, and neighbor contact.",8.5,"local",{}),
    Scene("Gene and movement","It changes gene expression and moves.",6.5,"local",{}),
    Scene("Coherent result","Yet the result can be one axis, one gut, one face, one organism.",8.5,"final",{}),
    Scene("Whole in parts","The whole appears in parts that cannot represent the whole.",7.5,"final",{}),
    Scene("Constraint","Sometimes the whole acts by changing what every part is allowed to do.",8.0,"constraint",{}),

    Scene("Upward causation","Developmental biology is filled with upward causation.",6.5,"upward",{}),
    Scene("Genes proteins","Genes produce proteins.",5.5,"upward",{}),
    Scene("Channels voltage","Ion channels generate voltage.",5.5,"upward",{}),
    Scene("Cells force","Cells exert force.",5.5,"upward",{}),
    Scene("Local tissue","Local interactions create tissue patterns.",6.5,"upward",{}),
    Scene("Indispensable mechanisms","A body cannot form without molecular and cellular mechanisms.",7.5,"upward",{}),
    Scene("Pattern relevance","Once a tissue pattern exists, can it alter the components that produced it?",8.5,"reality",{}),
    Scene("Whole causal story","Geometry, tension, and gradients bring the whole into the causal story.",8.0,"reality",{}),
    Scene("Not ghost","Not as a ghost. As constraint.",6.0,"constraint",{}),

    Scene("No pushing hand","A constraint does not need to push like a hand.",6.5,"constraint",{}),
    Scene("Riverbank","A riverbank changes water by limiting possible paths.",6.5,"constraint",{}),
    Scene("Musical key","A musical key changes which notes function as tension and resolution.",7.5,"constraint",{}),
    Scene("Traffic rules","Traffic rules change cars without entering their engines.",7.0,"constraint",{}),
    Scene("Space of possibilities","The whole structures the space of local possibilities.",7.0,"constraint",{}),
    Scene("Local mechanism remains","Each component still performs the immediate mechanism.",7.0,"constraint",{}),
    Scene("Global relevance","The larger pattern selects which mechanisms become relevant or coordinated.",8.5,"constraint",{}),
    Scene("No second force","Downward causation is local causation reorganized by global relation.",8.5,"constraint",{}),

    Scene("Embryonic polarity","Embryonic polarity offers a concrete example.",6.0,"axis",{}),
    Scene("Calcium tracks","Calcium-firing tracks propagate through extraembryonic tissue.",7.5,"axis",{}),
    Scene("BMP gradient","Local events interact with BMP signaling to produce a long-range gradient.",8.5,"axis",{}),
    Scene("Primitive streak","The primitive streak organizes a body axis.",6.5,"axis",{}),
    Scene("One streak","One streak supports one primary plan.",6.0,"axis",{}),
    Scene("Second streak","A second streak can initiate competing organization.",7.0,"axis",{"competing":True}),
    Scene("No single command","No single cell contains the command build exactly one axis.",8.0,"axis",{}),
    Scene("Parts field","Local calcium activity helps establish a global field.",7.5,"axis",{}),
    Scene("Field local fate","The global field changes what local regions can become.",7.5,"axis",{}),
    Scene("Constraint loop","Parts create the constraint. The constraint governs the parts.",8.0,"axis",{}),

    Scene("Regulation","This circularity is not optional decoration.",6.0,"position",{}),
    Scene("Size variation","Developing systems can regulate across changes in size.",7.5,"position",{}),
    Scene("Gradient span","A gradient spans a larger or smaller field.",6.5,"position",{}),
    Scene("Relative position","Cells interpret position relative to the whole.",7.0,"position",{}),
    Scene("Same signal different meaning","The same signal means differently in different locations.",8.0,"position",{}),
    Scene("No complete map","A cell does not need a complete map.",6.0,"position",{}),
    Scene("Signal in map","It needs a signal whose meaning depends on where it sits in the collective map.",9.0,"position",{}),
    Scene("Whole as position","The whole enters each part as positional information.",7.5,"position",{}),

    Scene("Tissue mechanics","Tissue mechanics works similarly.",6.0,"fold",{}),
    Scene("Cells pull","Cells pull on matrix and neighbors.",6.0,"fold",{}),
    Scene("Stress spans","Stress patterns stretch across tissue.",6.5,"fold",{}),
    Scene("Mechanics alter fate","Mechanical state alters signaling, nuclei, migration, and differentiation.",8.5,"fold",{}),
    Scene("Geometry feeds back","Geometry and tension feed back upon the cells that produced them.",8.5,"fold",{}),
    Scene("Fold contact","A fold changes surfaces. Contact changes signaling.",7.5,"fold",{}),
    Scene("Signaling growth","Signaling changes growth. Growth deepens the fold.",7.5,"fold",{}),
    Scene("Guides emergence","The whole emerges early enough to guide its own emergence.",8.0,"fold",{}),
    Scene("Body causes body","The body helps cause the body before the body is finished.",8.0,"fold",{}),

    Scene("Error correction","Developmental error correction is philosophically provocative.",7.0,"correction",{}),
    Scene("Compensate","Embryos can compensate for removed, displaced, or abnormal cells.",8.0,"correction",{}),
    Scene("Regenerate","Regenerating systems rebuild missing structures.",6.5,"correction",{}),
    Scene("Different routes","Different local routes can converge upon one large-scale outcome.",8.0,"correction",{}),
    Scene("Target whole","The system acts as though the target exists at the level of the whole.",8.0,"correction",{}),
    Scene("No engineer","No little engineer needs to visualize it.",6.0,"correction",{}),
    Scene("Distributed attractor","A stable anatomical attractor can be implemented through distributed feedback.",8.5,"correction",{}),
    Scene("Pattern correction","The target is causally real as a pattern of correction.",7.5,"correction",{}),
    Scene("Whole as error","The whole appears as the error the parts are collectively arranged to notice.",9.0,"correction",{}),

    Scene("Nested agents","Biological agents can be nested across scales.",6.5,"nested",{}),
    Scene("Cell competence","Cells have local competencies.",5.5,"nested",{}),
    Scene("Tissue goals","Tissues coordinate larger goals.",5.5,"nested",{}),
    Scene("Organs","Organs participate in organism-level regulation.",6.5,"nested",{}),
    Scene("Wider agent","A component can be competent while belonging to an agent with a larger problem space.",8.5,"nested",{}),
    Scene("Cancer conflict","Cancer illustrates conflict between local and whole-scale goals.",8.0,"nested",{"misaligned":True}),
    Scene("Local success","A lineage can pursue proliferation while destroying the organism.",8.0,"nested",{"misaligned":True}),
    Scene("Downward alignment","Downward causation constrains smaller goals through larger ones.",8.0,"nested",{}),
    Scene("Body present","Health requires the body to remain causally present to its cells.",8.0,"nested",{}),

    Scene("Beyond organism","Relevant wholes may sometimes extend beyond one organism.",7.5,"group",{}),
    Scene("Group resistance","Embryos in larger groups can be more resistant to developmental disruption.",8.5,"group",{}),
    Scene("Calcium ATP","Calcium and ATP signaling contribute to the effect.",7.0,"group",{}),
    Scene("No conscious cooperation","The finding does not show conscious cooperation.",7.0,"group",{}),
    Scene("Collective context","Developmental context can include signals exchanged among embryos.",8.0,"group",{}),
    Scene("Boundary depends","The regulatory whole depends upon the interaction.",7.0,"group",{}),
    Scene("Wholes form","Wholes can form where coordination becomes causally effective.",8.0,"group",{}),

    Scene("Plato direction","Platonic philosophy begins from a different direction.",7.0,"plato",{}),
    Scene("Participation in Forms","Sensible things are intelligible through participation in Forms.",8.0,"plato",{}),
    Scene("Form not assembled","The Form is not assembled from particular instances.",7.0,"plato",{}),
    Scene("Higher cause","Later Platonists give higher unities causal priority over multiplicity.",8.5,"plato",{}),
    Scene("Similarity caution","This resembles downward causation but does not confirm it.",8.0,"plato",{}),
    Scene("Different explanatory level","A Platonic Form is not a tissue constraint measurable in an embryo.",8.5,"plato",{}),
    Scene("Physical processes","Gradients, mechanics, and voltage are physical and manipulable.",8.0,"plato",{}),
    Scene("No detected realm","No developmental experiment detects the Form of Animal.",7.5,"plato",{}),
    Scene("Old question returns","Biology revives the question of how parts count as one organized thing.",8.5,"plato",{}),
    Scene("Mechanism and form","Mechanism tells how events occur; form tells which events belong to one process.",9.0,"plato",{}),

    Scene("Wholes fictional","The usual fear is that wholes are merely convenient summaries.",7.5,"reality",{}),
    Scene("Only cells real","Perhaps only cells are real.",6.0,"reality",{}),
    Scene("Intervention test","That view fails when organism-level variables improve prediction and intervention.",8.5,"reality",{}),
    Scene("Voltage outcome","Changing tissue voltage can alter anatomy without instructing every cell.",8.5,"reality",{}),
    Scene("Geometry fate","Mechanical geometry can change differentiation.",7.0,"reality",{}),
    Scene("Group size","Group size can change developmental resistance.",7.0,"reality",{}),
    Scene("Level makes difference","A higher-level description earns reality when differences there make differences below.",9.5,"reality",{}),
    Scene("Constraint works","The whole need not be a substance. It must be a constraint that works.",8.0,"reality",{}),

    Scene("Holism danger","The opposite danger is holism without mechanism.",7.0,"mechanism",{}),
    Scene("Body knew","The body knew what to do sounds explanatory but hides channels.",8.0,"mechanism",{}),
    Scene("Return downward","A serious account must return downward.",6.5,"mechanism",{}),
    Scene("Which channels","Which ion channels and gap junctions?",6.0,"mechanism",{}),
    Scene("Which sensors","Which mechanical sensors and pathways?",6.0,"mechanism",{}),
    Scene("Which regulation","Which gene-regulatory changes?",6.0,"mechanism",{}),
    Scene("Physical routes","The whole acts only through physically realized relations.",8.0,"mechanism",{}),
    Scene("Two directions meet","Mechanism and whole must meet.",6.5,"mechanism",{}),

    Scene("Proclus bridge","Proclus offers a useful analogy.",6.5,"participation",{}),
    Scene("Cause remains","A cause remains present in effects without being divided into them.",8.0,"participation",{}),
    Scene("Naturalistic echo","Biology offers a naturalistic echo.",6.0,"participation",{}),
    Scene("Pattern in behavior","Organism-level pattern is present in local behavior as constraint.",8.0,"participation",{}),
    Scene("Cell not body","A cell does not contain the body.",6.0,"participation",{}),
    Scene("Available actions","Its available actions are shaped by participation in bodily organization.",8.5,"participation",{}),
    Scene("Part and whole","The part is itself and what it can be only inside the whole.",8.0,"participation",{}),
    Scene("Analogy only","Proclean causality is metaphysical; biological constraint is experimentally tractable.",9.0,"plato",{}),

    Scene("Ethical analogy","The ethical analogy also requires care.",6.5,"social",{}),
    Scene("Institutions shape choices","Institutions, communities, and ecosystems shape local choices.",8.0,"social",{}),
    Scene("Harmful system","A harmful system can make destructive behavior individually rational.",8.0,"social",{}),
    Scene("Healthy system","A healthy system can make cooperation easier.",7.0,"social",{}),
    Scene("Field of incentives","The pattern acts through incentives, norms, architecture, information, and access.",8.5,"social",{}),
    Scene("No total understanding","No single person understands the whole system completely.",7.0,"social",{}),
    Scene("Whole in action","The whole is present in each action as a structured field of possibilities.",8.5,"social",{}),
    Scene("Replace individuals","Changing individuals without changing constraints often restores the same outcome.",8.5,"social",{}),
    Scene("Up and down","Social causation, like morphogenesis, moves upward and downward.",8.0,"social",{}),

    Scene("Return cell","No cell in an embryo understands the body.",6.5,"final",{}),
    Scene("Participation enough","Understanding is not required for participation.",6.0,"final",{}),
    Scene("Local signals carry whole","Local signals carry the influence of a larger organization.",8.0,"final",{}),
    Scene("Organization persists","Millions of responses let the organization persist and correct itself.",8.5,"final",{}),
    Scene("Not louder part","The whole is not another part with a louder voice.",7.5,"final",{}),
    Scene("Pattern changes meaning","It is the pattern that changes what every voice can mean.",8.0,"final",{}),
    Scene("Form priority","Plato gave form priority over scattered matter.",7.0,"plato",{}),
    Scene("Global constraint","Modern biology shows global form becoming a real constraint upon local mechanism.",9.0,"final",{}),
    Scene("No ghost no pile","The body is neither a ghost above cells nor a pile beneath a word.",8.0,"final",{}),
    Scene("Active agreement","It is the active agreement through which local lives become one unfinished cause.",9.0,"final",{}),
]

def render_frame(scene,frame_index,frame_count,width,height,seed):
    u=frame_index/max(1,frame_count-1); t=u*scene.duration
    dark=scene.visual=="attractor"
    im=background(width,height,seed,dark)
    VISUALS[scene.visual](im,u,t,scene.params)
    border(im,dark)
    return im.convert("RGB")

def require_ffmpeg():
    exe=shutil.which("ffmpeg")
    if not exe:raise RuntimeError("ffmpeg is required but was not found on PATH")
    return exe
def encode_scene(scene_index,fps):
    ffmpeg=require_ffmpeg(); frame_dir=FRAMES/f"scene_{scene_index:03d}"
    out=SCENES_DIR/f"scene_{scene_index:03d}.mp4"
    cmd=[ffmpeg,"-y","-framerate",str(fps),"-i",str(frame_dir/"%05d.jpg"),
         "-c:v","libx264","-preset","medium","-crf","18","-pix_fmt","yuv420p",
         "-movflags","+faststart",str(out)]
    subprocess.run(cmd,check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    return out
def render_scene(scene_index,scene,fps,width,height,preview):
    frame_dir=FRAMES/f"scene_{scene_index:03d}"
    frame_dir.mkdir(parents=True,exist_ok=True);SCENES_DIR.mkdir(parents=True,exist_ok=True)
    fc=max(2,round(scene.duration*fps))
    if preview:
        samples=[0,int(fc*.35),int(fc*.72),fc-1]
        for oi,fi in enumerate(samples):
            render_frame(scene,fi,fc,width,height,scene_index*1000+fi).save(frame_dir/f"preview_{oi:02d}.jpg",quality=95)
        return frame_dir
    for fi in range(fc):
        p=frame_dir/f"{fi:05d}.jpg"
        if p.exists():continue
        render_frame(scene,fi,fc,width,height,scene_index*1000+fi).save(p,quality=95,subsampling=0)
    return encode_scene(scene_index,fps)
def concatenate(paths):
    ffmpeg=require_ffmpeg(); c=OUTPUT/"concat.txt"
    c.write_text("\n".join(f"file '{p.resolve()}'" for p in paths),encoding="utf-8")
    out=OUTPUT/"the_whole_can_act_before_any_part_understands_it.mp4"
    subprocess.run([ffmpeg,"-y","-f","concat","-safe","0","-i",str(c),"-c","copy","-movflags","+faststart",str(out)],
                   check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    return out
def export_timeline():
    cursor=0;payload=[]
    for i,s in enumerate(SCENES,1):
        r=asdict(s);r["scene_id"]=f"scene_{i:03d}";r["start_seconds"]=round(cursor,3);r["end_seconds"]=round(cursor+s.duration,3)
        payload.append(r);cursor+=s.duration
    p=OUTPUT/"narration_timeline.json"
    p.write_text(json.dumps({
        "title":"the whole can act before any part understands it",
        "runtime_seconds":round(cursor,3),
        "scene_count":len(SCENES),
        "style":{
            "continuity_object":"gold global constraint field generated by local cells",
            "shot_duration_range_seconds":[5,10],
            "palette_roles":{
                "cyan":"local mechanism",
                "gold":"global constraint and positional information",
                "green":"integration and correction",
                "crimson":"competing organization and misalignment",
                "violet":"gene-regulatory interpretation",
                "graphite":"geometry and mechanics"
            }
        },
        "scenes":payload
    },indent=2,ensure_ascii=False),encoding="utf-8")
    return p
def make_contact_sheet(width,height):
    tw=320;th=int(tw*height/width);thumbs=[]
    for i,s in enumerate(SCENES,1):
        fc=max(2,round(s.duration*DEFAULT_FPS));im=render_frame(s,int(fc*.72),fc,width,height,i*1000+72)
        im.thumbnail((tw,th));thumbs.append((i,s.title,im.copy()))
    cols=4;rows=math.ceil(len(thumbs)/cols);cell_h=th+52
    sheet=Image.new("RGB",(cols*tw,rows*cell_h),WHITE);d=ImageDraw.Draw(sheet);font=load_font(FONT_SANS_BOLD,15)
    for idx,title,im in thumbs:
        slot=idx-1;x=(slot%cols)*tw;y=(slot//cols)*cell_h
        sheet.paste(im,(x,y));d.text((x+10,y+th+8),f"{idx:03d}  {title}",font=font,fill=INK)
    p=OUTPUT/"contact_sheet.jpg";sheet.save(p,quality=94);return p
def parse_args():
    p=argparse.ArgumentParser()
    p.add_argument("--fps",type=int,default=DEFAULT_FPS)
    p.add_argument("--width",type=int,default=DEFAULT_WIDTH)
    p.add_argument("--height",type=int,default=DEFAULT_HEIGHT)
    p.add_argument("--scene",type=int,default=None)
    p.add_argument("--preview",action="store_true")
    p.add_argument("--no-contact-sheet",action="store_true")
    return p.parse_args()
def main():
    args=parse_args()
    OUTPUT.mkdir(parents=True,exist_ok=True);FRAMES.mkdir(parents=True,exist_ok=True);SCENES_DIR.mkdir(parents=True,exist_ok=True)
    print(f"Timeline: {export_timeline()}")
    print(f"Scenes: {len(SCENES)}")
    print(f"Runtime: {sum(s.duration for s in SCENES)/60:.2f} minutes")
    if args.scene is not None:
        if not 1<=args.scene<=len(SCENES):raise ValueError(f"--scene must be between 1 and {len(SCENES)}")
        print(render_scene(args.scene,SCENES[args.scene-1],args.fps,args.width,args.height,args.preview));return
    rendered=[]
    for i,s in enumerate(SCENES,1):
        print(f"[{i:03d}/{len(SCENES):03d}] {s.title} ({s.duration:.1f}s)")
        r=render_scene(i,s,args.fps,args.width,args.height,args.preview)
        if not args.preview:rendered.append(r)
    if not args.no_contact_sheet:print(f"Contact sheet: {make_contact_sheet(args.width,args.height)}")
    if not args.preview:print(f"Final video: {concatenate(rendered)}")

if __name__=="__main__":
    main()
