#!/usr/bin/env python3
"""
YOUR SENSES ARE ALREADY EATING THE UNIVERSE
A complete Platinum-house procedural visual essay.

Source adapted from:
expansion-essays/02_your_senses_are_already_eating_the_universe.md

DESIGN CONTRACT
---------------
• Every shot lasts 5–10 seconds.
• Every shot visibly performs the narrated operation.
• White scientific-sacrificial field; concept-led color only.
• No static slide layouts and no decorative loops.
• Gold = sensory current / nectar / completed perception
• Cyan = active sense architecture / translation
• Crimson = appetite / appropriation / interrupted metabolism
• Violet = memory / concept / association
• Green = completed digestion / rest / viable action
• Graphite = practical distinction / boundary
• Sparse typography: terms function as seals, never paragraphs.
• Each mature frame around u=0.72 should work as a still.
• Continuity object: one gold sensory current survives across chapters.
• Organic imagery must dominate: membranes, tongues, cochlear spirals,
  retinal cups, capillaries, nectar, fire, digestion, circulation.
• Sacred geometry appears only when generated by bodily process.

OUTPUT
------
output_senses_eating/
  frames/scene_001/*.jpg
  scenes/scene_001.mp4
  your_senses_are_already_eating_the_universe.mp4
  narration_timeline.json
  contact_sheet.jpg

REQUIREMENTS
------------
pip install pillow numpy
ffmpeg must be on PATH.

USAGE
-----
python your_senses_are_already_eating_the_universe_platinum.py
python your_senses_are_already_eating_the_universe_platinum.py --preview
python your_senses_are_already_eating_the_universe_platinum.py --scene 8
python your_senses_are_already_eating_the_universe_platinum.py --fps 12 --width 1920 --height 1080
"""

from __future__ import annotations

import argparse
import json
import math
import random
import shutil
import subprocess
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Callable

import numpy as np
from PIL import Image, ImageDraw, ImageFilter, ImageFont


# =============================================================================
# CONFIGURATION
# =============================================================================

ROOT = Path(__file__).resolve().parent
OUTPUT = ROOT / "output_senses_eating"
FRAMES = OUTPUT / "frames"
SCENES_DIR = OUTPUT / "scenes"

DEFAULT_WIDTH = 1280
DEFAULT_HEIGHT = 720
DEFAULT_FPS = 10

WHITE = (248, 247, 243)
PAPER = (242, 239, 232)
INK = (29, 31, 35)
SOFT_INK = (86, 89, 94)
SILVER = (177, 184, 190)
PALE_SILVER = (223, 226, 228)
GOLD = (194, 151, 66)
PALE_GOLD = (235, 216, 169)
CYAN = (54, 150, 177)
PALE_CYAN = (191, 226, 233)
CRIMSON = (159, 49, 64)
PALE_CRIMSON = (231, 190, 197)
GREEN = (66, 139, 96)
PALE_GREEN = (193, 225, 205)
VIOLET = (104, 78, 145)
PALE_VIOLET = (215, 204, 231)
LAPIS = (48, 72, 126)
NECTAR = (225, 181, 78)
VOID = (22, 24, 30)

FONT_SERIF = "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf"
FONT_SERIF_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf"
FONT_SANS = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
FONT_SANS_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


# =============================================================================
# MATHEMATICS / DRAWING HELPERS
# =============================================================================

def clamp(x: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, x))


def lerp(a: float, b: float, t: float) -> float:
    return a + (b - a) * t


def mix(a: tuple[int, int, int], b: tuple[int, int, int], t: float) -> tuple[int, int, int]:
    t = clamp(t)
    return tuple(int(lerp(x, y, t)) for x, y in zip(a, b))


def smoothstep(a: float, b: float, x: float) -> float:
    if a == b:
        return 1.0 if x >= b else 0.0
    q = clamp((x - a) / (b - a))
    return q * q * (3.0 - 2.0 * q)


def ease(t: float) -> float:
    t = clamp(t)
    return 0.5 - 0.5 * math.cos(math.pi * t)


def ease_out(t: float) -> float:
    t = clamp(t)
    return 1.0 - (1.0 - t) ** 3


def pulse(t: float, hz: float = 1.0, phase: float = 0.0) -> float:
    return 0.5 + 0.5 * math.sin(math.tau * (hz * t + phase))


def load_font(path: str, size: int) -> ImageFont.ImageFont:
    for candidate in (path, FONT_SERIF, FONT_SANS):
        try:
            return ImageFont.truetype(candidate, size)
        except OSError:
            continue
    return ImageFont.load_default()


def rgba_layer(size: tuple[int, int]) -> Image.Image:
    return Image.new("RGBA", size, (0, 0, 0, 0))


def background(width: int, height: int, seed: int, dark: bool = False) -> Image.Image:
    rng = np.random.default_rng(seed)
    base = VOID if dark else WHITE
    arr = np.empty((height, width, 3), dtype=np.float32)
    arr[:] = base
    noise = rng.normal(0, 1.0 if not dark else 1.6, (height, width, 1))
    arr += noise
    arr = np.clip(arr, 0, 255).astype(np.uint8)
    im = Image.fromarray(arr, "RGB").convert("RGBA")
    return im


def centered_text(draw, xy, text, font, fill=INK):
    draw.text(xy, text, font=font, fill=fill, anchor="mm")


def seal(im: Image.Image, title: str, subtitle: str = "", color=INK) -> None:
    w, h = im.size
    d = ImageDraw.Draw(im)
    title_font = load_font(FONT_SERIF_BOLD, max(22, int(h * 0.042)))
    sub_font = load_font(FONT_SANS, max(13, int(h * 0.020)))
    centered_text(d, (w / 2, h * 0.875), title, title_font, color)
    if subtitle:
        centered_text(d, (w / 2, h * 0.925), subtitle, sub_font, SOFT_INK)


def border(im: Image.Image) -> None:
    w, h = im.size
    d = ImageDraw.Draw(im)
    d.rounded_rectangle((25, 25, w - 25, h - 25), radius=17, outline=(*INK, 46), width=2)


def glow_line(im, points, color, width=4, glow=14, alpha=225):
    if len(points) < 2:
        return
    layer = rgba_layer(im.size)
    d = ImageDraw.Draw(layer)
    d.line(points, fill=(*color, alpha), width=width, joint="curve")
    im.alpha_composite(layer.filter(ImageFilter.GaussianBlur(glow)))
    im.alpha_composite(layer)


def glow_circle(im, cx, cy, radius, color, alpha=180, blur=18):
    layer = rgba_layer(im.size)
    d = ImageDraw.Draw(layer)
    d.ellipse((cx-radius, cy-radius, cx+radius, cy+radius), fill=(*color, alpha))
    im.alpha_composite(layer.filter(ImageFilter.GaussianBlur(blur)))
    core = rgba_layer(im.size)
    ImageDraw.Draw(core).ellipse(
        (cx-radius*.42, cy-radius*.42, cx+radius*.42, cy+radius*.42),
        fill=(*mix(color, WHITE, .28), min(255, alpha+40)),
    )
    im.alpha_composite(core)


def partial_polyline(points, progress):
    progress = clamp(progress)
    if len(points) < 2:
        return points
    lengths = [math.dist(a, b) for a, b in zip(points[:-1], points[1:])]
    total = sum(lengths)
    target = total * progress
    output = [points[0]]
    walked = 0.0
    for i, length in enumerate(lengths):
        if walked + length <= target:
            output.append(points[i + 1])
            walked += length
        else:
            q = 0.0 if length == 0 else (target - walked) / length
            ax, ay = points[i]
            bx, by = points[i + 1]
            output.append((lerp(ax, bx, q), lerp(ay, by, q)))
            break
    return output


def arrow(draw, start, end, color=INK, width=3, head=12):
    draw.line((*start, *end), fill=color, width=width)
    angle = math.atan2(end[1]-start[1], end[0]-start[0])
    for delta in (2.55, -2.55):
        p=(end[0]+math.cos(angle+delta)*head,end[1]+math.sin(angle+delta)*head)
        draw.line((*end,*p), fill=color, width=width)


def organic_blob(draw, cx, cy, rx, ry, color, phase=0.0, points=90, outline=None):
    pts=[]
    for i in range(points):
        a=math.tau*i/points
        wob=1+.07*math.sin(a*3+phase)+.04*math.sin(a*7-phase*.7)
        pts.append((cx+math.cos(a)*rx*wob, cy+math.sin(a)*ry*wob))
    draw.polygon(pts, fill=color, outline=outline)
    return pts


def filament_path(w,h,phase=0.0,y=.45):
    pts=[]
    for i in range(200):
        q=i/199
        x=lerp(w*.08,w*.92,q)
        yy=h*y + math.sin(q*math.tau*2.2+phase)*h*.035 + math.sin(q*math.tau*6-phase*.6)*h*.012
        pts.append((x,yy))
    return pts


def draw_eye(draw,cx,cy,rx,ry,open_amount=1.0,color=INK):
    top=[]; bottom=[]
    for i in range(80):
        q=i/79
        x=lerp(cx-rx,cx+rx,q)
        arch=math.sin(q*math.pi)*ry*open_amount
        top.append((x,cy-arch)); bottom.append((x,cy+arch))
    draw.line(top,fill=(*color,220),width=4)
    draw.line(bottom,fill=(*color,220),width=4)
    draw.ellipse((cx-ry*.52,cy-ry*.52,cx+ry*.52,cy+ry*.52),fill=(*LAPIS,210),outline=(*INK,180),width=2)
    draw.ellipse((cx-ry*.18,cy-ry*.18,cx+ry*.18,cy+ry*.18),fill=(*VOID,240))


def draw_cochlea(draw,cx,cy,r,color=CYAN,turns=3.0,progress=1.0,width=5):
    pts=[]
    n=180
    for i in range(n):
        q=i/(n-1)
        a=q*math.tau*turns
        rr=r*(1-q*.82)
        pts.append((cx+math.cos(a)*rr,cy+math.sin(a)*rr))
    draw.line(partial_polyline(pts,progress),fill=(*color,220),width=width,joint="curve")


def draw_tongue(draw,cx,cy,wid,hei,color=PALE_CRIMSON):
    organic_blob(draw,cx,cy,wid,hei,(*color,245),phase=.7,outline=(*CRIMSON,170))
    for i in range(28):
        a=(i*137)%360
        rr=(.12+.74*((i*47)%29)/29)
        x=cx+math.cos(math.radians(a))*wid*rr
        y=cy+math.sin(math.radians(a))*hei*rr
        draw.ellipse((x-3,y-3,x+3,y+3),fill=(*CRIMSON,110))


# =============================================================================
# SCENE DATA
# =============================================================================

@dataclass
class Scene:
    title: str
    narration: str
    duration: float
    visual: str
    params: dict


# =============================================================================
# VISUAL MODES
# =============================================================================

def visual_sense_feast(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    q=ease(u)
    centers=[(w*.18,h*.39),(w*.40,h*.39),(w*.62,h*.39),(w*.82,h*.39)]
    draw_eye(d,*centers[0],70,33,1.0)
    draw_cochlea(d,*centers[1],42,CYAN,3.2,q,5)
    draw_tongue(d,*centers[2],58,34)
    organic_blob(d,*centers[3],58,58,(*PALE_CYAN,220),phase=t*.4,outline=(*CYAN,150))
    cols=[GOLD,CYAN,CRIMSON,VIOLET]
    for i,(cx,cy) in enumerate(centers):
        path=[(w*.50,h*.15),(lerp(w*.50,cx,.5),h*.26),(cx,cy)]
        glow_line(im,partial_polyline(path,smoothstep(i*.10,.62+i*.05,u)),cols[i],4,12,210)
    glow_circle(im,w*.50,h*.15,18,GOLD,170,12)
    seal(im,"EVERY PERCEPTION CONSUMES SOMETHING","color · vibration · chemistry · contact")


def visual_internal_sacrifice(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    cx,cy=w*.5,h*.43
    # black sacrificial depth edged with gold
    r=lerp(55,150,ease(u))
    organic_blob(d,cx,cy,r,r*.72,(*VOID,245),phase=t*.35,outline=(*GOLD,190))
    for i,col in enumerate((CYAN,CRIMSON,VIOLET,GREEN)):
        a=-1.8+i*1.2
        sx=cx+math.cos(a)*w*.31; sy=cy+math.sin(a)*h*.26
        pts=[(sx,sy),(lerp(sx,cx,.55),lerp(sy,cy,.55)-30*math.sin(t+i)),(cx,cy)]
        glow_line(im,partial_polyline(pts,smoothstep(.10+i*.08,.82,u)),col,4,13,190)
    glow_circle(im,cx,cy,28,GOLD,150,18)
    seal(im,"CONSCIOUSNESS BECOMES THE FIRE","objects enter as offerings; isolation burns away")


def visual_metabolic_belly(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    cx,cy=w*.52,h*.42
    outer=rgba_layer(im.size); od=ImageDraw.Draw(outer)
    organic_blob(od,cx,cy,w*.24,h*.23,(*PALE_CYAN,210),phase=t*.25,outline=(*CYAN,170))
    im.alpha_composite(outer)
    # streams digest into gold droplets
    rng=random.Random(33)
    for i in range(42):
        a=rng.uniform(0,math.tau); rr=rng.uniform(.15,1.0)
        sx=cx+math.cos(a)*w*.28*rr; sy=cy+math.sin(a)*h*.26*rr
        q=smoothstep(i*.005,.78,u)
        x=lerp(sx,cx,q); y=lerp(sy,cy,q)
        col=[CYAN,CRIMSON,VIOLET,GREEN][i%4]
        d.ellipse((x-3,y-3,x+3,y+3),fill=(*mix(col,GOLD,q),170))
    nectar=smoothstep(.48,.94,u)
    glow_circle(im,cx,cy,20+38*nectar,GOLD,int(100+110*nectar),16)
    seal(im,"SENSATION AS SACRED METABOLISM","difference is digested; experience becomes energy")


def visual_appetite_capture(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    obj=(w*.73,h*.40); eye=(w*.25,h*.40)
    draw_eye(d,*eye,88,42,1.0)
    organic_blob(d,*obj,72,72,(*PALE_GOLD,235),phase=t*.5,outline=(*GOLD,180))
    q=ease(u)
    path=[eye,(w*.48,h*.32),obj]
    glow_line(im,partial_polyline(path,q),GOLD,5,13,220)
    # object reverses and devours seer
    rev=smoothstep(.50,.95,u)
    if rev:
        jaws=[]
        for side in (-1,1):
            pts=[]
            for i in range(80):
                a=lerp(-1.2,1.2,i/79)
                x=lerp(obj[0],eye[0],i/79)
                y=lerp(obj[1],eye[1],i/79)+side*math.sin(i/79*math.pi)*55*rev
                pts.append((x,y))
            jaws.append(pts)
            d.line(pts,fill=(*CRIMSON,int(210*rev)),width=5)
        glow_circle(im,eye[0],eye[1],22,CRIMSON,int(120*rev),12)
    seal(im,"THE OBJECT CONSUMES THE SEER","appearance becomes lack, threat, identity, demand")


def visual_feast_not_hoard(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # one melody ribbon moves through an open hand-like field
    path=filament_path(w,h,t*.7,.42)
    glow_line(im,partial_polyline(path,ease(u)),GOLD,6,15,230)
    # hand arcs stay open
    for side in (-1,1):
        pts=[]
        for i in range(100):
            q=i/99
            x=lerp(w*.22,w*.78,q)
            y=h*.43+side*(80+40*math.sin(q*math.pi))
            pts.append((x,y))
        d.line(pts,fill=(*CYAN,150),width=4)
    # particles pass through, none trapped
    for i in range(18):
        q=(u+i/18)%1
        x=lerp(w*.12,w*.88,q); y=h*.42+math.sin(q*math.tau*2+t)*25
        d.ellipse((x-3,y-3,x+3,y+3),fill=(*GOLD,190))
    seal(im,"THEY FEAST · THEY DO NOT HOARD","appearance completes without becoming property")


def visual_rasa_theatre(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    colors=[CRIMSON,VIOLET,GOLD,CYAN]
    labels=["fear","grief","wonder","joy"]
    for i,(col,label) in enumerate(zip(colors,labels)):
        x=w*(.18+i*.21)
        q=smoothstep(i*.10,.65+i*.06,u)
        organic_blob(d,x,h*.40,58*q,82*q,(*mix(WHITE,col,.28),220),phase=t*.2+i,outline=(*col,170))
        if q>.62:
            centered_text(d,(x,h*.62),label.upper(),load_font(FONT_SANS_BOLD,int(h*.018)),col)
    # emotion streams merge into a shared rasa bowl
    bowl_y=h*.68
    d.arc((w*.30,bowl_y-80,w*.70,bowl_y+60),0,180,fill=(*GOLD,180),width=5)
    for i,col in enumerate(colors):
        x=w*(.18+i*.21)
        glow_line(im,partial_polyline([(x,h*.48),(w*.5,bowl_y)],smoothstep(.38,.92,u)),col,3,10,180)
    seal(im,"RASA","emotion released from immediate ownership")


def visual_bell_layers(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    sx=w*.18; cy=h*.42
    # source ring
    for j in range(6):
        rr=20+j*30*smoothstep(.05,.82,u)
        d.arc((sx-rr,cy-rr,sx+rr,cy+rr),-70,70,fill=(*GOLD,int(170*(1-j/7))),width=3)
    stages=[("contact",CYAN),("bell",GOLD),("memory",VIOLET),("reaction",CRIMSON)]
    for i,(label,col) in enumerate(stages):
        x=w*(.38+i*.15); q=smoothstep(i*.12,.55+i*.08,u)
        d.ellipse((x-28*q,cy-28*q,x+28*q,cy+28*q),fill=(*mix(WHITE,col,.20),int(230*q)),outline=(*col,int(190*q)),width=3)
        if q>.72: centered_text(d,(x,cy+55),label,load_font(FONT_SANS_BOLD,int(h*.016)),col)
        if i>0:
            d.line((w*(.38+(i-1)*.15)+28,cy,x-28,cy),fill=(*SOFT_INK,int(120*q)),width=2)
    # final offering back into fire
    fire=(w*.86,cy)
    glow_circle(im,*fire,25,GOLD,int(100+110*smoothstep(.58,.95,u)),14)
    glow_line(im,partial_polyline([(w*.83,cy),fire],smoothstep(.55,.92,u)),GOLD,4,11,210)
    seal(im,"OFFER THE NAMING TOO","sound · concept · memory · reaction become fuel")


def visual_distinction_not_isolation(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    centers=[(w*.30,h*.42),(w*.70,h*.42)]
    cols=[CRIMSON,CYAN]
    for (cx,cy),col in zip(centers,cols):
        organic_blob(d,cx,cy,85,105,(*mix(WHITE,col,.17),235),phase=t*.2+cx,outline=(*col,190))
    # retain distinct outlines; add relational mesh
    mesh=smoothstep(.18,.88,u)
    for i in range(9):
        y=h*(.24+i*.045)
        x1=w*.30+75*math.cos(i*.5); x2=w*.70-75*math.cos(i*.4)
        d.line((x1,y,x2,y+math.sin(i)*20),fill=(*GOLD,int(120*mesh)),width=2)
    centered_text(d,centers[0],"FIRE",load_font(FONT_SERIF_BOLD,int(h*.032)),CRIMSON)
    centered_text(d,centers[1],"WATER",load_font(FONT_SERIF_BOLD,int(h*.032)),CYAN)
    seal(im,"DISTINCTNESS IS REAL · ISOLATION IS IMAGINED","nonduality does not flatten practical difference")


def visual_sense_deities(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # one incoming field translated through 5 architectures
    names=[("VISION",LAPIS),("HEARING",CYAN),("TOUCH",GOLD),("TASTE",CRIMSON),("SMELL",VIOLET)]
    for i,(name,col) in enumerate(names):
        x=w*(.14+i*.18); q=smoothstep(i*.08,.62+i*.05,u)
        d.ellipse((x-46*q,h*.41-46*q,x+46*q,h*.41+46*q),fill=(*mix(WHITE,col,.15),int(225*q)),outline=(*col,int(190*q)),width=3)
        # unique inner grammar
        if i==0:
            d.line((x-28*q,h*.41,x+28*q,h*.41),fill=(*col,190),width=3)
            d.ellipse((x-10*q,h*.41-10*q,x+10*q,h*.41+10*q),fill=(*col,190))
        elif i==1:
            draw_cochlea(d,x,h*.41,25*q,col,2.4,q,3)
        elif i==2:
            for j in range(5): d.line((x,h*.41,x+math.cos(j*math.tau/5)*28*q,h*.41+math.sin(j*math.tau/5)*28*q),fill=(*col,170),width=2)
        elif i==3:
            draw_tongue(d,x,h*.41,30*q,17*q)
        else:
            for j in range(8):
                a=j*math.tau/8+t*.2
                d.ellipse((x+math.cos(a)*25*q-3,h*.41+math.sin(a)*25*q-3,x+math.cos(a)*25*q+3,h*.41+math.sin(a)*25*q+3),fill=(*col,160))
        if q>.7: centered_text(d,(x,h*.58),name,load_font(FONT_SANS_BOLD,int(h*.015)),col)
    seal(im,"THE SENSES ARE ACTIVE POWERS OF DISCLOSURE","the gods by which reality becomes lived")


def visual_feed_metabolism(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # conveyor of bright objects enters a dark stomach but fails to digest
    cx,cy=w*.65,h*.43
    organic_blob(d,cx,cy,145,125,(*VOID,245),phase=t*.25,outline=(*CRIMSON,180))
    for i in range(12):
        q=(u*1.8+i/12)%1
        x=lerp(w*.08,cx,q)
        y=h*.30+((i%3)-1)*55
        col=[GOLD,CYAN,VIOLET,CRIMSON][i%4]
        d.rounded_rectangle((x-25,y-18,x+25,y+18),radius=8,fill=(*mix(WHITE,col,.25),220),outline=(*col,150),width=2)
    # residual pile accumulates
    for i in range(30):
        x=cx-90+(i%10)*18; y=cy+65-(i//10)*12
        d.ellipse((x-4,y-4,x+4,y+4),fill=(*CRIMSON,150))
    seal(im,"INTERRUPTED METABOLISM","object after object enters attention; nothing completes")


def visual_nectar_completion(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # perception cycle: arise, enjoy, dissolve, fullness
    cx,cy=w*.5,h*.42
    r=w*.24
    stages=[("ARISE",CYAN),("ENJOY",GOLD),("DISSOLVE",VIOLET),("REST",GREEN)]
    for i,(label,col) in enumerate(stages):
        a=-math.pi/2+i*math.pi/2
        x=cx+math.cos(a)*r; y=cy+math.sin(a)*r*.62
        q=smoothstep(i*.12,.58+i*.08,u)
        glow_circle(im,x,y,18+15*q,col,int(100+90*q),11)
        if q>.62: centered_text(d,(x,y+48),label,load_font(FONT_SANS_BOLD,int(h*.016)),col)
        if i>0:
            ap=-math.pi/2+(i-1)*math.pi/2
            xp=cx+math.cos(ap)*r; yp=cy+math.sin(ap)*r*.62
            glow_line(im,partial_polyline([(xp,yp),(x,y)],q),mix(stages[i-1][1],col,.5),4,10,180)
    # central nectar pool
    glow_circle(im,cx,cy,28+45*smoothstep(.45,.95,u),NECTAR,170,18)
    seal(im,"NECTAR IS COMPLETED EXPERIENCE","the current finishes; awareness remains full")


def visual_precise_action(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    flame=(w*.68,h*.42)
    # flame
    pts=[]
    for i in range(100):
        q=i/99
        a=math.pi+q*math.pi
        rx=45*(1-.25*math.sin(q*math.pi))
        x=flame[0]+math.cos(a)*rx
        y=flame[1]+math.sin(a)*85
        pts.append((x,y))
    d.polygon(pts,fill=(*PALE_CRIMSON,230),outline=(*CRIMSON,190))
    # boundary moves into place
    bx=lerp(w*.82,w*.52,ease(u))
    d.line((bx,h*.18,bx,h*.68),fill=(*INK,220),width=6)
    # green action vector leaves calmly
    arrow(d,(w*.30,h*.43),(w*.42,h*.43),GREEN,5,14)
    # crimson reaction dissolves in gold fire behind
    for i in range(12):
        q=smoothstep(.22+i*.025,.82,u)
        x=lerp(w*.36,w*.50,q); y=h*.30+i*12
        d.ellipse((x-3,y-3,x+3,y+3),fill=(*mix(CRIMSON,GOLD,q),int(180*(1-.65*q))))
    seal(im,"ACTION REMAINS · HATRED NEED NOT","the boundary can be precise without becoming identity")


def visual_eating_practice(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # single bite, highly detailed
    plate=(w*.50,h*.48)
    d.ellipse((plate[0]-170,plate[1]-85,plate[0]+170,plate[1]+85),fill=(*PAPER,245),outline=(*SILVER,170),width=3)
    bite=(w*.5,h*.43)
    organic_blob(d,*bite,78,48,(*PALE_GOLD,245),phase=t*.3,outline=(*GOLD,180))
    stages=[("texture",CYAN),("temperature",CRIMSON),("fragrance",VIOLET),("leaning",GREEN),("demand",CRIMSON)]
    for i,(label,col) in enumerate(stages):
        a=-2.5+i*.7
        x=bite[0]+math.cos(a)*w*.22; y=bite[1]+math.sin(a)*h*.22
        q=smoothstep(i*.10,.56+i*.07,u)
        d.line((bite[0],bite[1],x,y),fill=(*col,int(150*q)),width=2)
        if q>.7: centered_text(d,(x,y),label,load_font(FONT_SANS_BOLD,int(h*.015)),col)
    # offer demand to center
    glow_circle(im,bite[0],bite[1],18+25*smoothstep(.55,.92,u),GOLD,160,14)
    seal(im,"ONE BITE","attention without possession lets taste complete")


def visual_thought_offering(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    phrases=[("I AM AFRAID",CRIMSON),("I AM RIGHT",VIOLET),("I NEED THIS",GOLD)]
    cx,cy=w*.50,h*.45
    for i,(text,col) in enumerate(phrases):
        x=w*(.22+i*.28); q=smoothstep(i*.10,.58+i*.07,u)
        d.rounded_rectangle((x-100*q,h*.25-28*q,x+100*q,h*.25+28*q),radius=18,fill=(*mix(WHITE,col,.14),int(230*q)),outline=(*col,int(180*q)),width=2)
        if q>.52: centered_text(d,(x,h*.25),text,load_font(FONT_SANS_BOLD,int(h*.018)),col)
        glow_line(im,partial_polyline([(x,h*.29),(cx,cy)],smoothstep(.32+i*.05,.88,u)),col,3,11,170)
    organic_blob(d,cx,cy,118,92,(*VOID,245),phase=t*.2,outline=(*GOLD,190))
    glow_circle(im,cx,cy,24,GOLD,160,14)
    seal(im,"IDENTITY BECOMES THE FIRE · NOT THE FUEL","thought appears within consciousness and is offered back")


def visual_sacrificer_enters(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    cx,cy=w*.5,h*.42
    # rings: body senses objects thoughts claimant
    rings=[("BODY",CYAN),("SENSES",GOLD),("OBJECTS",CRIMSON),("THOUGHTS",VIOLET),("CLAIMANT",INK)]
    for i,(label,col) in enumerate(rings):
        r=180-i*28
        fade=1-smoothstep(.08+i*.10,.72+i*.06,u)
        d.ellipse((cx-r,cy-r*.62,cx+r,cy+r*.62),outline=(*col,int(190*fade)),width=4)
        if fade>.2: centered_text(d,(cx,cy-r*.62-15),label,load_font(FONT_SANS_BOLD,int(h*.014)),(*col,int(180*fade)))
    # all collapse into open capacity
    q=ease(u)
    glow_circle(im,cx,cy,22+120*q,GOLD,int(100+100*q),22)
    seal(im,"THE SACRIFICER ALSO ENTERS THE FIRE","nothing remains outside to own the ritual")


def visual_final_nectar(im,u,t,p):
    w,h=im.size; d=ImageDraw.Draw(im)
    # all sensory organs around one open field; gold current completes
    cx,cy=w*.5,h*.42
    coords=[(w*.20,h*.35),(w*.35,h*.62),(w*.65,h*.62),(w*.80,h*.35)]
    draw_eye(d,*coords[0],62,30,1.0)
    draw_cochlea(d,*coords[1],38,CYAN,3.0,1.0,4)
    draw_tongue(d,*coords[2],48,27)
    organic_blob(d,*coords[3],48,48,(*PALE_CYAN,220),phase=t*.3,outline=(*CYAN,150))
    for i,pt in enumerate(coords):
        col=[LAPIS,CYAN,CRIMSON,VIOLET][i]
        glow_line(im,partial_polyline([pt,(cx,cy)],smoothstep(.05+i*.07,.65,u)),col,4,12,180)
    q=smoothstep(.35,.96,u)
    glow_circle(im,cx,cy,30+105*q,NECTAR,190,24)
    if q>.62:
        for i in range(28):
            a=i*math.tau/28+t*.08
            rr=50+90*q
            x=cx+math.cos(a)*rr; y=cy+math.sin(a)*rr*.65
            d.ellipse((x-3,y-3,x+3,y+3),fill=(*GOLD,int(160*(1-q*.3))))
    seal(im,"YOUR SENSES ARE ALREADY EATING THE UNIVERSE","hungry through grasping · divine through completion",GREEN)


VISUALS: dict[str, Callable] = {
    "sense_feast": visual_sense_feast,
    "internal_sacrifice": visual_internal_sacrifice,
    "metabolic_belly": visual_metabolic_belly,
    "appetite_capture": visual_appetite_capture,
    "feast_not_hoard": visual_feast_not_hoard,
    "rasa": visual_rasa_theatre,
    "bell_layers": visual_bell_layers,
    "distinction": visual_distinction_not_isolation,
    "sense_deities": visual_sense_deities,
    "feed": visual_feed_metabolism,
    "nectar": visual_nectar_completion,
    "action": visual_precise_action,
    "eating_practice": visual_eating_practice,
    "thought": visual_thought_offering,
    "sacrificer": visual_sacrificer_enters,
    "final": visual_final_nectar,
}


# =============================================================================
# FULL ADAPTED ESSAY / TIMED SHOT LIST
# =============================================================================

SCENES: list[Scene] = [
    Scene("Every perception consumes","Every perception consumes something.",5.5,"sense_feast",{}),
    Scene("Eye","The eye takes color.",5.0,"sense_feast",{}),
    Scene("Ear","The ear takes vibration.",5.0,"sense_feast",{}),
    Scene("Tongue","The tongue takes chemistry and turns it into taste.",6.5,"sense_feast",{}),
    Scene("Mind","The mind takes the result and says: mine, pleasant, dangerous, more.",8.0,"appetite_capture",{}),
    Scene("Not windows","You imagine the senses as windows through which the world enters.",6.5,"sense_feast",{}),
    Scene("Deities and offering","Abhinavagupta imagines something more violent and more beautiful. The senses are deities. The world is an offering.",9.0,"internal_sacrifice",{}),
    Scene("Fire","Consciousness is the fire into which difference is thrown.",7.0,"internal_sacrifice",{}),
    Scene("Eating universe","Your senses are already eating the universe.",6.0,"final",{}),

    Scene("Ritual relocated","In the Tantraloka, external sacrifice is relocated inside perception.",7.0,"internal_sacrifice",{}),
    Scene("Ground and powers","Consciousness becomes the sacrificial ground. The senses become divine powers. Objects become offerings.",9.0,"internal_sacrifice",{}),
    Scene("Isolation burns","The object is not physically destroyed. Its claim to independent isolation is burned away.",8.0,"distinction",{}),
    Scene("Not nothing","The world is not burned into nothing. Its imagined separateness is consumed.",7.0,"distinction",{}),

    Scene("Oblation depth","Existing things are cast into the oblation-consuming depth of consciousness.",7.0,"metabolic_belly",{}),
    Scene("Sense powers feast","The sense-powers feast upon the universe transformed into nectar.",7.0,"metabolic_belly",{}),
    Scene("Bodily imagery","Belly. Fire. Eating. Satisfaction.",6.5,"metabolic_belly",{}),
    Scene("Sacred metabolism","This is sensation understood as a sacred metabolic act.",7.0,"metabolic_belly",{}),
    Scene("Difference digested","The world enters consciousness. Difference is digested. Experience becomes energy.",9.0,"metabolic_belly",{}),

    Scene("Beautiful object","Ordinary perception also consumes, but badly. A beautiful object is converted into lack.",8.0,"appetite_capture",{}),
    Scene("Criticism identity","A voice becomes identity. Pleasure becomes planning before the taste has finished.",8.5,"appetite_capture",{}),
    Scene("Appropriation","The senses do not simply receive. They appropriate.",6.0,"appetite_capture",{}),
    Scene("Wrapped in use","The object is measured by what it can provide, threaten, confirm, or deny.",8.0,"appetite_capture",{}),
    Scene("Reversed sacrifice","Instead of offering differentiation into awareness, awareness is offered into differentiation.",9.0,"appetite_capture",{}),
    Scene("Object consumes seer","The object consumes the seer.",6.0,"appetite_capture",{}),

    Scene("Aesthetic shift","The Tantric shift is aesthetic rather than anaesthetic.",6.5,"feast_not_hoard",{}),
    Scene("No numbing","It does not numb the senses. It releases them from compulsory appetite.",7.5,"feast_not_hoard",{}),
    Scene("Melody unowned","A melody can be heard completely without being owned.",7.0,"feast_not_hoard",{}),
    Scene("Landscape unpossessed","A landscape can enter vision without becoming a resource.",7.0,"feast_not_hoard",{}),
    Scene("Face freed","A face can be beautiful without being made responsible for satisfying the one who sees it.",8.5,"feast_not_hoard",{}),
    Scene("Feast not hoard","The senses become divine when enjoyment no longer contracts the field around me and mine.",9.0,"feast_not_hoard",{}),

    Scene("Ritual and art","Here Abhinavagupta's philosophy of ritual meets his philosophy of art.",7.0,"rasa",{}),
    Scene("Suspended concern","In aesthetic experience, personal concern can be temporarily suspended.",7.0,"rasa",{}),
    Scene("Fear and grief","Fear in drama can be relished. Grief can become beautiful.",7.5,"rasa",{}),
    Scene("Wonder","Wonder expands without requiring possession.",6.5,"rasa",{}),
    Scene("Rasa","Emotion becomes universalized enough to be tasted as rasa.",8.0,"rasa",{}),
    Scene("Ownership dissolved","Experience is not denied. Its narrow ownership is dissolved.",7.5,"rasa",{}),

    Scene("Bell contact","Consider a bell: metal, vibration, air, ear.",7.0,"bell_layers",{}),
    Scene("Bell recognition","Then recognition: bell.",5.5,"bell_layers",{}),
    Scene("Bell association","Then association: temple, school, danger, memory.",8.0,"bell_layers",{}),
    Scene("Bell evaluation","Then evaluation: pleasant, annoying, meaningful, irrelevant.",8.0,"bell_layers",{}),
    Scene("Catch before appropriation","Catch the sound before appropriation completes itself.",7.5,"bell_layers",{}),
    Scene("Offer naming","Let vibration unfold. Let the mind name it. Then offer the naming too.",9.0,"bell_layers",{}),
    Scene("Everything fuel","Sound, concept, memory, reaction: everything becomes fuel.",8.0,"bell_layers",{}),

    Scene("Difference misunderstood","The sacrifice of differentiation is easy to misunderstand.",6.5,"distinction",{}),
    Scene("Cup and flame","A cup does not cease to be different from a flame.",6.5,"distinction",{}),
    Scene("Not extension","Another person does not become an extension of your wishes.",7.0,"distinction",{}),
    Scene("Not flattening","Nonduality is not the flattening of practical distinctions.",7.0,"distinction",{}),
    Scene("Isolation imagined","Distinctness is real. Isolation is imagined.",6.5,"distinction",{}),
    Scene("Fire and water","Fire remains fire. Water remains water. Both lose the fantasy of independence.",9.0,"distinction",{}),

    Scene("Not passive holes","The senses are not passive holes in the body.",6.0,"sense_deities",{}),
    Scene("Vision","Vision organizes light into depth, color, edge, and movement.",8.0,"sense_deities",{}),
    Scene("Hearing","Hearing separates streams from vibration.",7.0,"sense_deities",{}),
    Scene("Touch","Touch gives texture, pressure, warmth, and boundary.",7.5,"sense_deities",{}),
    Scene("Taste smell","Taste and smell bind chemistry to memory and value.",7.5,"sense_deities",{}),
    Scene("Gods of experience","The senses are the gods by which reality becomes experience.",8.0,"sense_deities",{}),

    Scene("Attention economy","Modern attention systems understand this hunger.",6.5,"feed",{}),
    Scene("Advertising lack","Advertising trains the senses to convert appearances into deficiency.",8.0,"feed",{}),
    Scene("Notification","The notification says something outside the present is more important than the present.",8.5,"feed",{}),
    Scene("Feed","The feed offers a sacrifice without completion.",7.0,"feed",{}),
    Scene("Nothing digested","Object after object enters attention, but nothing is digested.",8.0,"feed",{}),
    Scene("Interrupted metabolism","The senses keep eating and remain unsatisfied.",7.0,"feed",{}),

    Scene("Divine satisfaction","The divine sense-powers become satisfied because the universe is transformed into nectar.",9.0,"nectar",{}),
    Scene("Not stimulation","Nectar is not endless stimulation.",6.0,"nectar",{}),
    Scene("Freed from grasping","It is experience freed from the roughness of grasping.",7.0,"nectar",{}),
    Scene("Cycle completes","Perception arises. The object is enjoyed. Its form dissolves. Awareness remains full.",10.0,"nectar",{}),
    Scene("No debt","No residue of metaphysical debt is left behind.",6.5,"nectar",{}),

    Scene("Needs remain","This does not eliminate ordinary needs.",6.0,"action",{}),
    Scene("Danger remains","Hunger asks for food. Danger must be distinguished from beauty.",7.0,"action",{}),
    Scene("Not harmful enjoyment","The practice is not a command to enjoy harmful conditions or ignore bodily limits.",8.5,"action",{}),
    Scene("Precise action","Move away from the flame. Set the boundary. Refuse the demand.",8.0,"action",{}),
    Scene("Reaction consumed","Action can remain precise while awareness consumes the reaction.",8.0,"action",{}),

    Scene("Begin with eating","The practice can begin with eating. Take one bite.",6.5,"eating_practice",{}),
    Scene("Before naming","Before naming the food, notice texture, temperature, pressure, fragrance.",8.5,"eating_practice",{}),
    Scene("Leaning","Notice the body leaning toward or away.",6.5,"eating_practice",{}),
    Scene("Memory attaches","Notice memory attaching itself.",6.0,"eating_practice",{}),
    Scene("Demand appears","Notice the moment pleasure becomes demand for the next bite.",8.0,"eating_practice",{}),
    Scene("Offer demand","Do not condemn the demand. Offer it.",6.5,"eating_practice",{}),
    Scene("Circuit closes","The tongue receives the world. Consciousness receives the tongue. The circuit closes.",9.0,"eating_practice",{}),

    Scene("Thought as object","The same practice applies to thought. A thought is also an object.",7.0,"thought",{}),
    Scene("Thought shape","It appears with shape, tone, urgency, and implied action.",7.0,"thought",{}),
    Scene("Identification","Ordinarily the mind consumes thought by identifying with it.",7.0,"thought",{}),
    Scene("I am afraid","I am afraid. I am right. I need this.",7.0,"thought",{}),
    Scene("Ownership reversed","Internal sacrifice reverses ownership.",6.5,"thought",{}),
    Scene("Appears within","Fear, rightness, and need appear within consciousness.",8.0,"thought",{}),
    Scene("Identity fire","Identity becomes the fire rather than the fuel.",7.0,"thought",{}),

    Scene("Deepest offering","The deepest offering is the one who believes they are performing the sacrifice.",9.0,"sacrificer",{}),
    Scene("Imperial nonduality","If the ego says I consume the universe into my consciousness, nonduality becomes imperial possession.",9.5,"sacrificer",{}),
    Scene("Sacrificer enters","The sacrificer must also enter the fire.",7.0,"sacrificer",{}),
    Scene("Private centre","The sense of being a private centre outside experience is another appearance.",8.5,"sacrificer",{}),
    Scene("All offered","Body, senses, objects, thoughts, and the one claiming them are offered into one open capacity.",10.0,"sacrificer",{}),
    Scene("Rest in Bhairava","Nothing remains outside to own the ritual. The culmination is rest in Bhairava.",9.0,"sacrificer",{}),

    Scene("Return","Every perception consumes something.",5.5,"final",{}),
    Scene("Eye and ear","The eye takes color. The ear takes vibration.",6.5,"final",{}),
    Scene("Mind builds world","The mind takes the result and builds a world.",6.5,"final",{}),
    Scene("Another eating","But perception can become another kind of eating.",6.5,"final",{}),
    Scene("Forms unprisoned","The senses receive forms without imprisoning them.",7.0,"final",{}),
    Scene("Difference intimacy","Difference enters the fire and returns as intimacy.",7.5,"final",{}),
    Scene("Nectar","The universe becomes nectar because it no longer needs to complete the one tasting it.",9.0,"final",{}),
    Scene("Question","Do the senses remain hungry because nothing is enough, or become divine because every appearance is allowed to dissolve into fullness?",10.0,"final",{}),
]


# =============================================================================
# RENDER PIPELINE
# =============================================================================

def render_frame(scene: Scene, frame_index: int, frame_count: int,
                 width: int, height: int, seed: int) -> Image.Image:
    u = frame_index / max(1, frame_count - 1)
    t = u * scene.duration
    im = background(width, height, seed, dark=False)
    VISUALS[scene.visual](im, u, t, scene.params)
    border(im)
    return im.convert("RGB")


def require_ffmpeg() -> str:
    executable = shutil.which("ffmpeg")
    if not executable:
        raise RuntimeError("ffmpeg is required but was not found on PATH")
    return executable


def encode_scene(scene_index: int, fps: int) -> Path:
    ffmpeg = require_ffmpeg()
    frame_dir = FRAMES / f"scene_{scene_index:03d}"
    output_path = SCENES_DIR / f"scene_{scene_index:03d}.mp4"
    command = [
        ffmpeg, "-y",
        "-framerate", str(fps),
        "-i", str(frame_dir / "%05d.jpg"),
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "18",
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        str(output_path),
    ]
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return output_path


def render_scene(scene_index: int, scene: Scene, fps: int,
                 width: int, height: int, preview: bool) -> Path:
    frame_dir = FRAMES / f"scene_{scene_index:03d}"
    frame_dir.mkdir(parents=True, exist_ok=True)
    SCENES_DIR.mkdir(parents=True, exist_ok=True)

    frame_count = max(2, round(scene.duration * fps))
    if preview:
        samples = [0, int(frame_count*.35), int(frame_count*.72), frame_count-1]
        for out_idx, frame_idx in enumerate(samples):
            image = render_frame(scene, frame_idx, frame_count, width, height, scene_index*1000+frame_idx)
            image.save(frame_dir / f"preview_{out_idx:02d}.jpg", quality=95)
        return frame_dir

    for frame_idx in range(frame_count):
        path = frame_dir / f"{frame_idx:05d}.jpg"
        if path.exists():
            continue
        image = render_frame(scene, frame_idx, frame_count, width, height, scene_index*1000+frame_idx)
        image.save(path, quality=95, subsampling=0)

    return encode_scene(scene_index, fps)


def concatenate(scene_paths: list[Path]) -> Path:
    ffmpeg = require_ffmpeg()
    concat_file = OUTPUT / "concat.txt"
    concat_file.write_text(
        "\n".join(f"file '{path.resolve()}'" for path in scene_paths),
        encoding="utf-8",
    )
    output_path = OUTPUT / "your_senses_are_already_eating_the_universe.mp4"
    command = [
        ffmpeg, "-y",
        "-f", "concat", "-safe", "0",
        "-i", str(concat_file),
        "-c", "copy",
        "-movflags", "+faststart",
        str(output_path),
    ]
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return output_path


def export_timeline() -> Path:
    cursor = 0.0
    payload = []
    for index, scene in enumerate(SCENES, start=1):
        record = asdict(scene)
        record["scene_id"] = f"scene_{index:03d}"
        record["start_seconds"] = round(cursor, 3)
        record["end_seconds"] = round(cursor + scene.duration, 3)
        payload.append(record)
        cursor += scene.duration

    path = OUTPUT / "narration_timeline.json"
    path.write_text(json.dumps({
        "title": "your senses are already eating the universe",
        "runtime_seconds": round(cursor, 3),
        "scene_count": len(SCENES),
        "style": {
            "background": "clean white scientific-sacrificial field",
            "continuity_object": "gold sensory current",
            "shot_duration_range_seconds": [5, 10],
            "palette_roles": {
                "gold": "sensory current, nectar, completed perception",
                "cyan": "sense architecture and translation",
                "crimson": "appetite and appropriation",
                "violet": "memory, concept, association",
                "green": "completion, rest, viable action",
                "graphite": "practical distinction and boundary",
            },
        },
        "scenes": payload,
    }, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


def make_contact_sheet(width: int, height: int) -> Path:
    thumbs = []
    thumb_w = 320
    thumb_h = int(thumb_w * height / width)
    for index, scene in enumerate(SCENES, start=1):
        frame_count = max(2, round(scene.duration * DEFAULT_FPS))
        im = render_frame(scene, int(frame_count*.72), frame_count, width, height, index*1000+72)
        im.thumbnail((thumb_w, thumb_h))
        thumbs.append((index, scene.title, im.copy()))

    columns = 4
    rows = math.ceil(len(thumbs)/columns)
    cell_h = thumb_h + 52
    sheet = Image.new("RGB", (columns*thumb_w, rows*cell_h), WHITE)
    d = ImageDraw.Draw(sheet)
    label_font = load_font(FONT_SANS_BOLD, 15)

    for idx, title, im in thumbs:
        slot = idx-1
        x = (slot%columns)*thumb_w
        y = (slot//columns)*cell_h
        sheet.paste(im, (x,y))
        d.text((x+10,y+thumb_h+8), f"{idx:02d}  {title}", font=label_font, fill=INK)

    path = OUTPUT / "contact_sheet.jpg"
    sheet.save(path, quality=94)
    return path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fps", type=int, default=DEFAULT_FPS)
    parser.add_argument("--width", type=int, default=DEFAULT_WIDTH)
    parser.add_argument("--height", type=int, default=DEFAULT_HEIGHT)
    parser.add_argument("--scene", type=int, default=None,
                        help="Render one 1-indexed scene only.")
    parser.add_argument("--preview", action="store_true",
                        help="Render four representative stills per scene, not MP4.")
    parser.add_argument("--no-contact-sheet", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    FRAMES.mkdir(parents=True, exist_ok=True)
    SCENES_DIR.mkdir(parents=True, exist_ok=True)

    timeline = export_timeline()
    print(f"Timeline: {timeline}")
    print(f"Scenes: {len(SCENES)}")
    print(f"Runtime: {sum(s.duration for s in SCENES)/60:.2f} minutes")

    if args.scene is not None:
        if not 1 <= args.scene <= len(SCENES):
            raise ValueError(f"--scene must be between 1 and {len(SCENES)}")
        scene = SCENES[args.scene-1]
        result = render_scene(args.scene, scene, args.fps, args.width, args.height, args.preview)
        print(result)
        return

    rendered = []
    for index, scene in enumerate(SCENES, start=1):
        print(f"[{index:02d}/{len(SCENES):02d}] {scene.title} ({scene.duration:.1f}s)")
        result = render_scene(index, scene, args.fps, args.width, args.height, args.preview)
        if not args.preview:
            rendered.append(result)

    if not args.no_contact_sheet:
        sheet = make_contact_sheet(args.width, args.height)
        print(f"Contact sheet: {sheet}")

    if not args.preview:
        final = concatenate(rendered)
        print(f"Final video: {final}")


if __name__ == "__main__":
    main()
